### PR TITLE
Return sub-term from unification

### LINKED ISSUE #2067: Internal error: expected constructor-like patterns on KWasm update to K
On the UpdateDeps branch of KWasm (commit https://github.com/kframework/wasm-semantics/pull/373/commits/86d1aa6377588faa006d53945fcb9e6deb0bba65), I get the following error:

```
kore-exec: [48513122] Error (ErrorException):
    Internal error: expected constructor-like patterns, an internal invariant has been violated. Please report this error.
      Non-constructor-like patterns:
        /* D Sfc */
        /* Inj: */ inj{SortInt{}, SortKItem{}}(/* D Sfa */ \top{_PREDICATE{}}())
    CallStack (from HasCallStack):
      error, called at src/Kore/Internal/TermLike.hs:466:14 in kore-0.27.0.0-9PwdjC8MaAqGQuMlzrzvaj:Kore.Internal.TermLike
      assertConstructorLikeKeys, called at src/Kore/Builtin/AssociativeCommutative.hs:430:7 in kore-0.27.0.0-9PwdjC8MaAqGQuMlzrzvaj:Kore.Builtin.AssociativeCommutative
Created bug report: kore-exec.tar.gz
```

I've attached the generated `kore-exec.tar.gz`: 
[kwasm-bug.tar.gz](https://github.com/kframework/kore/files/5070770/kwasm-bug.tar.gz)

### PR DESCRIPTION
**Pull request by ttuegel**
The unified sub-term should be returned by all unification functions so that intermediate terms can be reconstructed. This is needed not only for `\and` simplification, but `\equals` and `\in` simplification as well.

Fixes #2067

- [x] `\equals` simplification
- [x] `\in` simplification

---

###### Reviewer checklist

- [ ] Test coverage: `stack test --coverage`
- [ ] Public API documentation: `stack haddock`

### CODE REVIEW

File: kore/src/Kore/Step/Simplification/Equals.hs [hunk 1]
```diff
@@ -441,10 +441,14 @@ termEqualsAnd p1 p2 =
                 Logic.scatter
             . sequence
         equalsPredicate =
```
Comment (ana-pantilie) [inline kore/src/Kore/Step/Simplification/Equals.hs:443]: Maybe this should be renamed to `equalsPattern`?

**Review by ana-pantilie — APPROVED** [review]

File: kore/src/Kore/Step/Simplification/Equals.hs (hunk 1 above)
Comment (ana-pantilie) [reply kore/src/Kore/Step/Simplification/Equals.hs]: I took care of this as my clean-up commit. I couldn't find anything else to refactor.
