### PR TITLE
Include result.kore with --bug-report

### LINKED ISSUE #2018: Include result.kore in --bug-report output
In `writeOptionsAndKoreFiles`, we should save the output `result.kore` as well as the input files.

### PR DESCRIPTION
**Pull request by emarzion**
Fixes #2018

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

File: kore/app/exec/Main.hs [hunk 1]
```diff
@@ -510,6 +510,7 @@ writeOptionsAndKoreFiles
     opts@KoreExecOptions
         { definitionFileName
         , patternFileName
+        --, outputFileName
```
Comment (ttuegel) [inline kore/app/exec/Main.hs:513]:
```suggestion
```

File: kore/app/exec/Main.hs [hunk 2]
```diff
@@ -528,6 +529,9 @@ writeOptionsAndKoreFiles
         (reportDirectory </> defaultDefinitionFilePath opts)
     for_ patternFileName
         $ flip copyFile (reportDirectory </> "pgm.kore")
+    -- for_ outputFileName
+    --    $ flip copyFile (reportDirectory </> "result.kore")
+    -- _ <- error "Test."
```
Comment (ttuegel) [inline kore/app/exec/Main.hs:534]:
```suggestion
```

File: kore/app/exec/Main.hs [hunk 3]
```diff
@@ -558,20 +562,14 @@ main = do
...
     ensureSmtPreludeExists koreSolverOptions
     exitCode <-
         withBugReport Main.exeName bugReportOption $ \tmpDir -> do
             writeOptionsAndKoreFiles tmpDir execOptions
-            go <* warnIfLowProductivity
-                & handle handleWithConfiguration
-                & handle handleSomeException
-                & runKoreLog tmpDir koreLogOptions
+            e <- code tmpDir
+            for_ outputFileName $ flip copyFile (tmpDir </> "result.kore")
```
Comment (ttuegel) [inline kore/app/exec/Main.hs:571]: This will only capture the output if it is being written to a file already. It will not capture the standard output. We should write the output to a temporary file _first_, and copy the file or print it to standard output afterward.

**Review by ttuegel — CHANGES_REQUESTED** [review]

File: kore/app/exec/Main.hs [hunk 4]
```diff
@@ -594,21 +596,21 @@ mainWithOptions execOptions = do
             ("// Last configuration:\n" <> unparse lastConfiguration)
         throwM someException
 
-    go :: Main ExitCode
-    go
+    go :: KoreExecOptions -> Main ExitCode
```
Comment (ttuegel) [inline kore/app/exec/Main.hs:599]: Because we are passing `KoreExecOptions` into this function now, can we extract it to the top level?

**Review by ttuegel — APPROVED** [review]
