### PR TITLE
kore-repl: If piped commands fail do not crash kore-repl

### LINKED ISSUE #2903: kore-repl: if piped commands fail do not crash kore-repl

### PR DESCRIPTION
**Pull request by andreiburdusa**
Fixes #2903

Before:
```
Welcome to the Kore Repl! Use 'help' to get started.

Kore (0)> claim | error
kore-repl: [4284482] Error (ErrorException):
    fd:43: commitBuffer: resource vanished (Broken pipe)
Created bug report: kore-repl.tar.gz
[Error] Critical: Haskell Backend execution failed with code 1 and produced no
output.
```
After:
```
Welcome to the Kore Repl! Use 'help' to get started.

Kore (0)> claim | error
fd:43: commitBuffer: resource vanished (Broken pipe)
You are currently proving claim 0
Kore (0)> 
```

where `error` is an empty script

### Estimate: December 9

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

File: kore/src/Kore/Repl/Interpreter.hs [hunk 1]
```diff
@@ -1243,7 +1244,9 @@ pipe cmd file args = do
     runExternalProcess pipeOut exec str = do
         (maybeInput, maybeOutput, _, _) <- createProcess' exec
         let outputFunc = maybe putStrLn hPutStr maybeInput
```
Comment (dopamane) [inline kore/src/Kore/Repl/Interpreter.hs:1246]: I realize this isn't directly related to the issue at hand but it should be cleaned up while we have the opportunity. `createProcess'` uses `CreatePipe` for both `std_in` and `std_out` so the input and output handles will always be `Just` (see [System.Process](https://hackage.haskell.org/package/process-1.6.13.2/docs/System-Process.html#v:createProcess)). Therefore `outputFunc` will always be `hPutStr`. So we can replace `outputFunc` with `hPutStr hOut` everywhere in the function (line 1249) and just write `(Just hIn, Just hOut, _, _) <- createProcess' exec`. We can also then cleanup the `case maybeOutput` to:
```
output <- liftIO $ hGetContents hOut
modifyIORef pipeOut (appReplOut . AuxOut $ output
```
No need to handle the `Nothing` case anymore.

Comment (dopamane) [reply kore/src/Kore/Repl/Interpreter.hs:1246]:
```haskell
(Just hIn, Just hOut, _, _) <- createProcess' exec
X.handle
  (\(X.SomeException e) -> hPutStrLn stderr (displayException e))
  (hPutStr hIn str)
output <- liftIO $ hGetContents hOut
modifyIORef pipeOut (appReplOut . AuxOut $ output)
```

Comment (dopamane) [reply kore/src/Kore/Repl/Interpreter.hs:1246]: Perhaps using `catch` is tidier:
```haskell
hPutStr hIn str `catch` \X.SomeException e -> hPutStrLn stderr (displayException e)
```

**Review by ana-pantilie — APPROVED** [review]

**Review by dopamane — APPROVED** [review]
