### PR TITLE
Reset SMT solver

### LINKED ISSUE #2075: Error `Failed to decide predicate` for in_keys
Executing erc20 on kore `b2f05a7506f01ebdab9a48a1310e0a1b076675ce` leads to this error:

```
kore-exec: [818482874] Error (ErrorDecidePredicateUnknown):
    (InfoReachability) while applying axioms:
    (InfoAttemptUnification) while attempting unification:
    (DebugAttemptEquation) while applying equation at /home/jenkins-slave/workspace/erc20-verification_PR-32@2/.build/specs-compiled/haskell/symbolic/mainnet-make/02_bnb/lemmas.k:26:10-27:68:
    (DebugAttemptEquation) while applying equation at /home/jenkins-slave/workspace/erc20-verification_PR-32@2/deps/evm-semantics/evm-types.md:668:34-668:129:
    (DebugEvaluateCondition) while evaluating predicate:
    Failed to decide predicate:
...
    with side condition:
...
```

Pretty printed term above:
```
 #Not ( {
  false
#Equals
  keccak ( #buf ( 32 , ?ACCT ) ++ b"0000000000000000000000000000000000000000000000000000000000000004" ) in_keys ( ?_STORAGE )
} )
```

The error appears during evaluation of this rule:
```
rule [#lookup.none]:         #lookup(                          M, KEY ) => 0                 requires notBool KEY in_keys(M)
```

Expected outcome: `#lookup` term should stay unevaluated

Full error:
```
kore-exec: [818482874] Error (ErrorDecidePredicateUnknown):
    (InfoReachability) while applying axioms:
    (InfoAttemptUnification) while attempting unification:
    (DebugAttemptEquation) while applying equation at /home/jenkins-slave/workspace/erc20-verification_PR-32@2/.build/specs-compiled/haskell/symbolic/mainnet-make/02_bnb/lemmas.k:26:10-27:68:
    (DebugAttemptEquation) while applying equation at /home/jenkins-slave/workspace/erc20-verification_PR-32@2/deps/evm-semantics/evm-types.md:668:34-668:129:
    (DebugEvaluateCondition) while evaluating predicate:
    Failed to decide predicate:

	#Not #Equals #False { keccak(_++_(#buf(32, ?ACCT), "0000000000000000000000000000000000000000000000000000000000000004"))??::KItem in_keys(?_STORAGE) }

        /* Sfc */
        \not{R}(
            /* Sfc */
            \equals{SortBool{}, R}(
                /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortBool{}}("false"),
                /* Fl Fn D Sfc */
                Lbl'Unds'in'Unds'keys'LParUndsRParUnds'MAP'Unds'Bool'Unds'KItem'Unds'Map{}(
                    /* Fl Fn D Sfc */
                    /* Inj: */ inj{SortInt{}, SortKItem{}}(
                        /* Fl Fn D Sfa */
                        Lblkeccak'LParUndsRParUnds'SERIALIZATION'Unds'Int'Unds'ByteArray{}(
                            /* Fl Fn D Sfa */
                            Lbl'UndsPlusPlusUndsUnds'EVM-TYPES'Unds'ByteArray'Unds'ByteArray'Unds'ByteArray{}(
                                /* Fl Fn D Sfa */
                                Lbl'Hash'buf'LParUndsCommUndsRParUnds'EDSL'Unds'ByteArray'Unds'Int'Unds'Int{}(
                                    /* Fl Fn D Sfa Cl */
                                    /* builtin: */ \dv{SortInt{}}("32"),
                                    /* Fl Fn D Sfa */ Var'Ques'ACCT:SortInt{}
                                ),
                                /* Fl Fn D Sfa Cl */
                                \dv{SortBytes{}}(
                                    "0000000000000000000000000000000000000000000000000000000000000004"
                                )
                            )
                        )
                    ),
                    /* Fl Fn D Sfa */ Var'QuesUnds'STORAGE:SortMap{}
                )
            )
        )
    with side condition:
        \and{SortGeneratedTopCell{}}(
            /* Sfa */
            \equals{SortBool{}, SortGeneratedTopCell{}}(
                /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortBool{}}("false"),
                /* Fl Fn D Sfa */
                Lbl'UndsEqlsEqls'Int'Unds'{}(
                    /* Fl Fn D Sfa */ Var'Ques'ACCT0:SortInt{},
                    /* Fl Fn D Sfa */ Var'Ques'ACCT:SortInt{}
                )
            ),
        \and{SortGeneratedTopCell{}}(
            /* Sfc */
            \equals{SortBool{}, SortGeneratedTopCell{}}(
                /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortBool{}}("false"),
                /* Fl Fn D Sfc */
                LblSet'Coln'in{}(
                    /* Fl Fn D Sfc */
                    /* Inj: */ inj{SortInt{}, SortKItem{}}(
                        /* Fl Fn D Sfa */ Var'Ques'ACCT:SortInt{}
                    ),
                    /* Fl Fn D Sfa Cl */
                    /* builtin: */
                    Lbl'Unds'Set'Unds'{}(
                        /* concrete element: */ LblSetItem{}(
                            /* Fl Fn D Sfa Cli */
                            /* Inj: */ inj{SortInt{}, SortKItem{}}(
                                /* Fl Fn D Sfa Cl */
                                /* builtin: */ \dv{SortInt{}}("1")
                            )
                        ),
                    Lbl'Unds'Set'Unds'{}(
                        /* concrete element: */ LblSetItem{}(
                            /* Fl Fn D Sfa Cli */
                            /* Inj: */ inj{SortInt{}, SortKItem{}}(
                                /* Fl Fn D Sfa Cl */
                                /* builtin: */ \dv{SortInt{}}("2")
                            )
                        ),
                    Lbl'Unds'Set'Unds'{}(
                        /* concrete element: */ LblSetItem{}(
                            /* Fl Fn D Sfa Cli */
                            /* Inj: */ inj{SortInt{}, SortKItem{}}(
                                /* Fl Fn D Sfa Cl */
                                /* builtin: */ \dv{SortInt{}}("3")
                            )
                        ),
                    Lbl'Unds'Set'Unds'{}(
                        /* concrete element: */ LblSetItem{}(
                            /* Fl Fn D Sfa Cli */
                            /* Inj: */ inj{SortInt{}, SortKItem{}}(
                                /* Fl Fn D Sfa Cl */
                                /* builtin: */ \dv{SortInt{}}("4")
                            )
                        ),
                    Lbl'Unds'Set'Unds'{}(
                        /* concrete element: */ LblSetItem{}(
                            /* Fl Fn D Sfa Cli */
                            /* Inj: */ inj{SortInt{}, SortKItem{}}(
                                /* Fl Fn D Sfa Cl */
                                /* builtin: */ \dv{SortInt{}}("5")
                            )
                        ),
                    Lbl'Unds'Set'Unds'{}(
                        /* concrete element: */ LblSetItem{}(
                            /* Fl Fn D Sfa Cli */
                            /* Inj: */ inj{SortInt{}, SortKItem{}}(
                                /* Fl Fn D Sfa Cl */
                                /* builtin: */ \dv{SortInt{}}("6")
                            )
                        ),
                    Lbl'Unds'Set'Unds'{}(
                        /* concrete element: */ LblSetItem{}(
                            /* Fl Fn D Sfa Cli */
                            /* Inj: */ inj{SortInt{}, SortKItem{}}(
                                /* Fl Fn D Sfa Cl */
                                /* builtin: */ \dv{SortInt{}}("7")
                            )
                        ),
                    Lbl'Unds'Set'Unds'{}(
                        /* concrete element: */ LblSetItem{}(
                            /* Fl Fn D Sfa Cli */
                            /* Inj: */ inj{SortInt{}, SortKItem{}}(
                                /* Fl Fn D Sfa Cl */
                                /* builtin: */ \dv{SortInt{}}("8")
                            )
                        ),
                        /* concrete element: */ LblSetItem{}(
                            /* Fl Fn D Sfa Cli */
                            /* Inj: */ inj{SortInt{}, SortKItem{}}(
                                /* Fl Fn D Sfa Cl */
                                /* builtin: */ \dv{SortInt{}}("9")
                            )
                        )
                    ))))))))
                )
            ),
        \and{SortGeneratedTopCell{}}(
            /* Sfc */
            \equals{SortBool{}, SortGeneratedTopCell{}}(
                /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortBool{}}("false"),
                /* Fl Fn D Sfc */
                LblSet'Coln'in{}(
                    /* Fl Fn D Sfc */
                    /* Inj: */ inj{SortInt{}, SortKItem{}}(
                        /* Fl Fn D Sfa */ Var'Ques'ACCT0:SortInt{}
                    ),
                    /* Fl Fn D Sfa Cl */
                    /* builtin: */
                    Lbl'Unds'Set'Unds'{}(
                        /* concrete element: */ LblSetItem{}(
                            /* Fl Fn D Sfa Cli */
                            /* Inj: */ inj{SortInt{}, SortKItem{}}(
                                /* Fl Fn D Sfa Cl */
                                /* builtin: */ \dv{SortInt{}}("1")
                            )
                        ),
                    Lbl'Unds'Set'Unds'{}(
                        /* concrete element: */ LblSetItem{}(
                            /* Fl Fn D Sfa Cli */
                            /* Inj: */ inj{SortInt{}, SortKItem{}}(
                                /* Fl Fn D Sfa Cl */
                                /* builtin: */ \dv{SortInt{}}("2")
                            )
                        ),
                    Lbl'Unds'Set'Unds'{}(
                        /* concrete element: */ LblSetItem{}(
                            /* Fl Fn D Sfa Cli */
                            /* Inj: */ inj{SortInt{}, SortKItem{}}(
                                /* Fl Fn D Sfa Cl */
                                /* builtin: */ \dv{SortInt{}}("3")
                            )
                        ),
                    Lbl'Unds'Set'Unds'{}(
                        /* concrete element: */ LblSetItem{}(
                            /* Fl Fn D Sfa Cli */
                            /* Inj: */ inj{SortInt{}, SortKItem{}}(
                                /* Fl Fn D Sfa Cl */
                                /* builtin: */ \dv{SortInt{}}("4")
                            )
                        ),
                    Lbl'Unds'Set'Unds'{}(
                        /* concrete element: */ LblSetItem{}(
                            /* Fl Fn D Sfa Cli */
                            /* Inj: */ inj{SortInt{}, SortKItem{}}(
                                /* Fl Fn D Sfa Cl */
                                /* builtin: */ \dv{SortInt{}}("5")
                            )
                        ),
                    Lbl'Unds'Set'Unds'{}(
                        /* concrete element: */ LblSetItem{}(
                            /* Fl Fn D Sfa Cli */
                            /* Inj: */ inj{SortInt{}, SortKItem{}}(
                                /* Fl Fn D Sfa Cl */
                                /* builtin: */ \dv{SortInt{}}("6")
                            )
                        ),
                    Lbl'Unds'Set'Unds'{}(
                        /* concrete element: */ LblSetItem{}(
                            /* Fl Fn D Sfa Cli */
                            /* Inj: */ inj{SortInt{}, SortKItem{}}(
                                /* Fl Fn D Sfa Cl */
                                /* builtin: */ \dv{SortInt{}}("7")
                            )
                        ),
                    Lbl'Unds'Set'Unds'{}(
                        /* concrete element: */ LblSetItem{}(
                            /* Fl Fn D Sfa Cli */
                            /* Inj: */ inj{SortInt{}, SortKItem{}}(
                                /* Fl Fn D Sfa Cl */
                                /* builtin: */ \dv{SortInt{}}("8")
                            )
                        ),
                        /* concrete element: */ LblSetItem{}(
                            /* Fl Fn D Sfa Cli */
                            /* Inj: */ inj{SortInt{}, SortKItem{}}(
                                /* Fl Fn D Sfa Cl */
                                /* builtin: */ \dv{SortInt{}}("9")
                            )
                        )
                    ))))))))
                )
            ),
        \and{SortGeneratedTopCell{}}(
            /* Sfa */
            \equals{SortBool{}, SortGeneratedTopCell{}}(
                /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortBool{}}("true"),
                /* Fl Fn D Sfa */
                Lbl'Unds-LT-'Int'Unds'{}(
                    /* Fl Fn D Sfa */ Var'Ques'ACCT:SortInt{},
                    /* Fl Fn D Sfa Cl */
                    /* builtin: */
                    \dv{SortInt{}}("1461501637330902918203684832716283019655932542976")
                )
            ),
        \and{SortGeneratedTopCell{}}(
            /* Sfa */
            \equals{SortBool{}, SortGeneratedTopCell{}}(
                /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortBool{}}("true"),
                /* Fl Fn D Sfa */
                Lbl'Unds-LT-'Int'Unds'{}(
                    /* Created: Kore.Step.RewriteStep.getResultPattern */
                    /* Fl Fn D Sfa */
                    Var'Ques'ACCT0:SortInt{},
                    /* Fl Fn D Sfa Cl */
                    /* builtin: */
                    \dv{SortInt{}}("1461501637330902918203684832716283019655932542976")
                )
            ),
        \and{SortGeneratedTopCell{}}(
            /* Sfa */
            \equals{SortBool{}, SortGeneratedTopCell{}}(
                /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortBool{}}("true"),
                /* Fl Fn D Sfa */
                Lbl'Unds-LT-'Int'Unds'{}(
                    /* Created: Kore.Step.RewriteStep.getResultPattern */
                    /* Fl Fn D Sfa */
                    Var'Ques'ACCT1:SortInt{},
                    /* Fl Fn D Sfa Cl */
                    /* builtin: */
                    \dv{SortInt{}}("1461501637330902918203684832716283019655932542976")
                )
            ),
        \and{SortGeneratedTopCell{}}(
            /* Sfa */
            \equals{SortBool{}, SortGeneratedTopCell{}}(
                /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortBool{}}("true"),
                /* Fl Fn D Sfa */
                Lbl'Unds-LT-'Int'Unds'{}(
                    /* Created: Kore.Step.RewriteStep.getResultPattern */
                    /* Fl Fn D Sfa */
                    Var'Ques'ACCT2:SortInt{},
                    /* Fl Fn D Sfa Cl */
                    /* builtin: */
                    \dv{SortInt{}}("1461501637330902918203684832716283019655932542976")
                )
            ),
        \and{SortGeneratedTopCell{}}(
            /* Sfa */
            \equals{SortBool{}, SortGeneratedTopCell{}}(
                /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortBool{}}("true"),
                /* Fl Fn D Sfa */
                Lbl'Unds-LT-'Int'Unds'{}(
                    /* Created: Kore.Step.RewriteStep.getResultPattern */
                    /* Fl Fn D Sfa */
                    Var'Ques'ACCT3:SortInt{},
                    /* Fl Fn D Sfa Cl */
                    /* builtin: */
                    \dv{SortInt{}}("1461501637330902918203684832716283019655932542976")
                )
            ),
        \and{SortGeneratedTopCell{}}(
            /* Sfa */
            \equals{SortBool{}, SortGeneratedTopCell{}}(
                /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortBool{}}("true"),
                /* Fl Fn D Sfa */
                Lbl'Unds-LT-'Int'Unds'{}(
                    /* Created: Kore.Step.RewriteStep.getResultPattern */
                    /* Fl Fn D Sfa */
                    Var'Ques'ACCT4:SortInt{},
                    /* Fl Fn D Sfa Cl */
                    /* builtin: */
                    \dv{SortInt{}}("1461501637330902918203684832716283019655932542976")
                )
            ),
        \and{SortGeneratedTopCell{}}(
            /* Sfa */
            \equals{SortBool{}, SortGeneratedTopCell{}}(
                /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortBool{}}("true"),
                /* Fl Fn D Sfa */
                Lbl'Unds-LT-'Int'Unds'{}(
                    /* Fl Fn D Sfa */ Var'Ques'SYMB'Unds'INT:SortInt{},
                    /* Fl Fn D Sfa Cl */
                    /* builtin: */
                    \dv{SortInt{}}("115792089237316195423570985008687907853269984665640564039457584007913129639936")
                )
            ),
        \and{SortGeneratedTopCell{}}(
            /* Sfa */
            \equals{SortBool{}, SortGeneratedTopCell{}}(
                /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortBool{}}("true"),
                /* Fl Fn D Sfa */
                Lbl'Unds-LT-Eqls'Int'Unds'{}(
                    /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("0"),
                    /* Fl Fn D Sfa */ Var'Ques'ACCT:SortInt{}
                )
            ),
        \and{SortGeneratedTopCell{}}(
            /* Sfa */
            \equals{SortBool{}, SortGeneratedTopCell{}}(
                /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortBool{}}("true"),
                /* Fl Fn D Sfa */
                Lbl'Unds-LT-Eqls'Int'Unds'{}(
                    /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("0"),
                    /* Created: Kore.Step.RewriteStep.getResultPattern */
                    /* Fl Fn D Sfa */
                    Var'Ques'ACCT0:SortInt{}
                )
            ),
        \and{SortGeneratedTopCell{}}(
            /* Sfa */
            \equals{SortBool{}, SortGeneratedTopCell{}}(
                /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortBool{}}("true"),
                /* Fl Fn D Sfa */
                Lbl'Unds-LT-Eqls'Int'Unds'{}(
                    /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("0"),
                    /* Created: Kore.Step.RewriteStep.getResultPattern */
                    /* Fl Fn D Sfa */
                    Var'Ques'ACCT1:SortInt{}
                )
            ),
        \and{SortGeneratedTopCell{}}(
            /* Sfa */
            \equals{SortBool{}, SortGeneratedTopCell{}}(
                /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortBool{}}("true"),
                /* Fl Fn D Sfa */
                Lbl'Unds-LT-Eqls'Int'Unds'{}(
                    /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("0"),
                    /* Created: Kore.Step.RewriteStep.getResultPattern */
                    /* Fl Fn D Sfa */
                    Var'Ques'ACCT2:SortInt{}
                )
            ),
        \and{SortGeneratedTopCell{}}(
            /* Sfa */
            \equals{SortBool{}, SortGeneratedTopCell{}}(
                /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortBool{}}("true"),
                /* Fl Fn D Sfa */
                Lbl'Unds-LT-Eqls'Int'Unds'{}(
                    /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("0"),
                    /* Created: Kore.Step.RewriteStep.getResultPattern */
                    /* Fl Fn D Sfa */
                    Var'Ques'ACCT3:SortInt{}
                )
            ),
        \and{SortGeneratedTopCell{}}(
            /* Sfa */
            \equals{SortBool{}, SortGeneratedTopCell{}}(
                /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortBool{}}("true"),
                /* Fl Fn D Sfa */
                Lbl'Unds-LT-Eqls'Int'Unds'{}(
                    /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("0"),
                    /* Created: Kore.Step.RewriteStep.getResultPattern */
                    /* Fl Fn D Sfa */
                    Var'Ques'ACCT4:SortInt{}
                )
            ),
        \and{SortGeneratedTopCell{}}(
            /* Sfa */
            \equals{SortBool{}, SortGeneratedTopCell{}}(
                /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortBool{}}("true"),
                /* Fl Fn D Sfa */
                Lbl'Unds-LT-Eqls'Int'Unds'{}(
                    /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("0"),
                    /* Fl Fn D Sfa */ Var'Ques'SYMB'Unds'INT:SortInt{}
                )
            ),
        \and{SortGeneratedTopCell{}}(
            /* Sfa */
            \not{SortGeneratedTopCell{}}(
                /* Spa */
                \equals{SortInt{}, SortGeneratedTopCell{}}(
                    /* Fl Fn D Sfa */ Var'Ques'ACCT:SortInt{},
                    /* Fl Fn D Sfa */ Var'Ques'ACCT0:SortInt{}
                )
            ),
        \and{SortGeneratedTopCell{}}(
            /* Sfa */
            \not{SortGeneratedTopCell{}}(
                /* Spa */
                \equals{SortInt{}, SortGeneratedTopCell{}}(
                    /* Fl Fn D Sfa */ Var'Ques'ACCT:SortInt{},
                    /* Fl Fn D Sfa */ Var'Ques'ACCT1:SortInt{}
                )
            ),
        \and{SortGeneratedTopCell{}}(
            /* Sfa */
            \not{SortGeneratedTopCell{}}(
                /* Spa */
                \equals{SortInt{}, SortGeneratedTopCell{}}(
                    /* Fl Fn D Sfa */ Var'Ques'ACCT:SortInt{},
                    /* Fl Fn D Sfa */ Var'Ques'ACCT2:SortInt{}
                )
            ),
            /* Sfa */
            \not{SortGeneratedTopCell{}}(
                /* Spa */
                \equals{SortInt{}, SortGeneratedTopCell{}}(
                    /* Fl Fn D Sfa */ Var'Ques'ACCT1:SortInt{},
                    /* Fl Fn D Sfa */ Var'Ques'ACCT2:SortInt{}
                )
            )
        ))))))))))))))))))))
```

### LINKED ISSUE #2078: Unit tests should not invoke SMT solver
Most unit tests should not invoke the SMT solver. This is where most time is spent in the unit tests, and reducing that time would improve the developers' experience. It's also just a good design principle to test components separately.

### LINKED ISSUE #2087: Reset the SMT solver at specific points
To avoid issues such as #2075, we will reset the SMT solver at specific points during execution. We believe this will also solve the memory leak associated with having a long-running Z3 process in incremental mode.

Fixes: #2075 
Before: #2072 

---

- [ ] Change type [`SMT`](https://github.com/kframework/kore/blob/master/kore/src/SMT.hs#L257) so that `ReaderT` carries a record with one field, `mSolverHandle :: !(MVar SolverHandle)`.
- [ ] Add a field to the record `userInit :: !(SMT ())` which will hold the code to initialize the SMT solver. [`runSMT`](https://github.com/kframework/kore/blob/master/kore/src/SMT.hs#L436) shall initialize this field with `return ()`.
- [ ] Factor the initialization code out of [`newSolver`](https://github.com/kframework/kore/blob/master/kore/src/SMT.hs#L409) into a new function `initSolver`. Use `initSolver` in [`runSMT'`](https://github.com/kframework/kore/blob/master/kore/src/SMT.hs#L441).
- [ ] Also call the `userInit` code in `initSolver`.
- [ ] Add an argument to `runSMT` for the initialization code. Where `runSMT` is called, move calls to `declareSMTLemmas` into the initialization argument.
- [ ] Add a method `reinit :: ()` to `MonadSMT`. The instance for `NoSMT` should do nothing. The instance for `SMT` should send the command `reset` and then call `initSolver`.
- [ ] Call `reinit` at the start of each proof step (after #2021, which will refactor the proof step).

### PR DESCRIPTION
**Pull request by andreiburdusa**
Fixes #2087 
Fixes #2075 
Fixes #2078 

---

###### Reviewer checklist

- [ ] Test coverage: `stack test --coverage`
- [ ] Public API documentation: `stack haddock`

### CODE REVIEW

File: kore/src/SMT.hs [hunk 1]
```diff
@@ -433,13 +462,14 @@ stopSolver mvar = do
...
-runSMT' :: MVar SolverHandle -> SMT a -> LoggerT IO a
-runSMT' mvar SMT { getSMT } = runReaderT getSMT mvar
+runSMT :: Config -> SMT () -> SMT a -> LoggerT IO a
+runSMT config userInit smt =
+    Exception.bracket (newSolver config userInit) stopSolver
+        (\mvar -> runSMT' config mvar smt)
+
+runSMT' :: Config -> MVar SolverHandle -> SMT a -> LoggerT IO a
+runSMT' config mvar SMT { getSMT } =
+    runReaderT getSMT (SolverInitAndHandle (initSolver config) mvar)
```
Comment (ttuegel) [inline kore/src/SMT.hs:472]:
```suggestion
    runReaderT (initSolver config >> getSMT) (SolverInitAndHandle userInit mvar)
```

File: kore/src/SMT.hs [hunk 2]
```diff
@@ -333,6 +356,10 @@ instance MonadSMT SMT where
     loadFile path =
         withSolver' $ \solver -> SimpleSMT.loadFile solver path
 
+    reinit = do
+        withSolver' $ \solver -> SimpleSMT.send solver (List [Atom "reset"])
+        initSolver defaultConfig
```
Comment (ttuegel) [inline kore/src/SMT.hs:361]:
```suggestion
        initSolver config?
```

File: kore/src/SMT.hs [hunk 3]
```diff
@@ -333,6 +357,11 @@ instance MonadSMT SMT where
     loadFile path =
         withSolver' $ \solver -> SimpleSMT.loadFile solver path
 
+    reinit = do
+        withSolver' $ \solver -> SimpleSMT.send solver (List [Atom "reset"])
```
Comment (ttuegel) [inline kore/src/SMT.hs:361]: Use `SimpleSMT.simpleCommand` instead.

File: kore/src/SMT.hs [hunk 4]
```diff
@@ -388,27 +417,29 @@ defaultConfig =
...
-newSolver config =
+newSolver :: Config -> SMT () -> LoggerT IO (MVar SolverHandle)
+newSolver config userInit =
     Exception.handle handleIOException $ do
         someLogAction <- Log.askLogAction
         mvar <- Trans.liftIO $ do
             solverHandle <- SimpleSMT.newSolver exe args someLogAction
             newMVar solverHandle
-        runReaderT getSMT mvar
+        runReaderT getSMT (SolverInitAndHandle userInit mvar config)
```
Comment (ttuegel) [inline kore/src/SMT.hs:438]:
```suggestion
```

File: kore/test/Test/SMT.hs [hunk 5]
```diff
@@ -55,7 +55,7 @@ assertEqual'
 assertEqual' str expect = liftIO . assertEqual str expect
 
 runSMT :: SMT a -> IO a
```
Comment (ttuegel) [inline kore/test/Test/SMT.hs:57]: 1. Extra `userInit` argument here.
2. Find uses of `declareSMTLemmas` in the tests. Use `runSMT` with `declareSMTLemmas` call as the extra argument.
3. Anywhere that we use `runSMT` without `declareSMTLemmas`, replace with `runNoSMT`.

File: kore/test/Test/Kore/Step/Simplification.hs [hunk 6]
```diff
@@ -63,23 +69,35 @@ import Kore.Step.Simplification.Data
...
     ( NoSMT
     )
-
 import qualified Test.SMT as Test
 
 runSimplifier :: Env Simplifier -> Simplifier a -> IO a
-runSimplifier env = Test.runSMT . Kore.runSimplifier env
+runSimplifier env = Test.runSMT userInit . Kore.runSimplifier env
+  where
+    userInit =
```
Comment (ttuegel) [inline kore/test/Test/Kore/Step/Simplification.hs:89]: I think this should really be:

```suggestion
    userInit = SMT.AST.declare (smtDeclarations metadataTools)
```
as [here](https://github.com/kframework/kore/blob/master/kore/test/Test/Kore/Strategies/Common.hs#L86). You will need to remove the latter.
