### PR TITLE
Simplify claims with side conditions

### LINKED ISSUE #1547: Term not simplified before first step
Steps to reproduce:

1. Use this branch: https://github.com/virgil-serbanuta/evm-semantics/tree/hkg-haskell-issue-1
2. Run this: 
```
rm -rf .build/defn
make defn
kompile --debug --main-module ETHEREUM-SIMULATION --backend haskell --hook-namespaces KRYPTO --syntax-module ETHEREUM-SIMULATION .build/defn/haskell/driver.k --directory .build/defn/haskell -I .build/defn/haskell
```
3. Run this: 
```
kprove --haskell-backend-command "/home/???/kore/.build/kore/bin/kore-repl " tests/specs/erc20/hkg/allowance-spec.k -d ./.build/defn/haskell --def-module VERIFICATION --debug -v
```
4. Note that the `<callData>` cell contains (indirectly) the following term, which is marked as being simplified conditionally (`Sfc`):
```
/* Fn Sfc */
Lbl'Hash'getValue'LParUndsRParUnds'EDSL'Unds'Int'Unds'TypedArg{}(
    /* Fl Fn D Sfa */
    Lbl'Hash'address'LParUndsRParUnds'EDSL'Unds'TypedArg'Unds'Int{}(
        /* Fl Fn D Sfa */
        VarOWNER:SortInt{}
    )
)
```
However, we should be able to simplify that term with this rule from https://github.com/virgil-serbanuta/evm-semantics/blob/hkg-haskell-issue-1/edsl.md :
```
rule #getValue(#address( DATA )) => DATA
      requires #rangeAddress(DATA)
```
@yzhang90 says that we should be able to apply this using the condition from the initial term. Also this seems to be simplified after the first step.

### PR DESCRIPTION
**Pull request by ttuegel**
Include the `requires` clause of a claim as its side condition during initial simplification.

Fixes: #1547

---

###### Reviewer checklist

- [ ] Test coverage: `stack test --coverage`
- [ ] Public API documentation: `stack haddock`

### CODE REVIEW

File: kore/src/Kore/Step/Rule/Simplify.hs [hunk 1]
```diff
@@ -131,18 +132,27 @@ instance SimplifyRuleLHS (ReachabilityRule Variable) where
...
+    . Lens.traverseOf RulePattern.leftPattern worker
   where
-    RulePattern {left, requires} = rule
+    worker, simplify, simplifyWithSolver
+        :: Pattern variable
+        -> BranchT simplifier (Pattern variable)
+    worker =
+        (return . Pattern.requireDefined)
+        >=> simplify
+        >=> simplifyWithSolver
```
Comment (virgil-serbanuta) [inline kore/src/Kore/Step/Rule/Simplify.hs]: We usually call `SMT.Evaluator.filterMultiOr` on the result of `simplifyTopConfiguration` instead of, say, `simplifyConditionsWithSmt` because we assume that the condition is already fully simplified (implied by the function name).

File: kore/test/Test/Kore/Step/Rule/Simplify.hs [hunk 2]
```diff
@@ -223,3 +243,76 @@ runSimplifyRule rule =
...
+        left = Lens.view (field @"left") rule
+        sort = termLikeSort left
+
+    test
+        :: HasCallStack
+        => TestName
+        -> RulePattern Variable
+        -> [RulePattern Variable]
+        -> TestTree
+    test name (OnePathRule -> input) (map OnePathRule -> expect) =
```
Comment (virgil-serbanuta) [inline kore/test/Test/Kore/Step/Rule/Simplify.hs]: You can leave it as-is if you want (this is a rather small test file), but I would be tempted to make it more obvious that this test uses the `g(a) => f(a)` mapping below, possibly by sending it as an argument.
