### PR TITLE
Ease reproducible bug report submission

### LINKED ISSUE #1800: Difficult to submit reproducible bug report
It is too difficult to submit a reproducible bug report. To debug an issue, we need all the Kore files used during execution, the exact command-line arguments to `kore-exec`, and the full text of any error message. The Kore files and command-line arguments to `kore-exec` are not normally available to the user.

---

- [ ] Add a command-line option `--bug-report` which captures the required inputs in a `.tar.gz` archive.
- [ ] Also create a bug report archive whenever an error is encountered.

### PR DESCRIPTION
**Pull request by andreiburdusa**
---
Fixes #1800 
###### Reviewer checklist

- [ ] Test coverage: `stack test --coverage`
- [ ] Public API documentation: `stack haddock`

### CODE REVIEW

File: kore/app/exec/Main.hs [hunk 1]
```diff
@@ -394,6 +419,58 @@ parserInfoModifiers =
...
+        , "koreMergeOptions = " <> show koreMergeOptions
+        , "rtsStatistics = " <> show rtsStatistics
+        ]
+
+writeOptionsAndKoreFiles :: KoreExecOptions -> IO ()
+writeOptionsAndKoreFiles
+    opts@KoreExecOptions { definitionFileName , patternFileName, outputFileName}
+  = do
+    createDirectoryIfMissing False "./report"
+    writeFile "./report/KoreExecOptions.txt" . showKoreExecOptions $ opts
```
Comment (ttuegel) [inline kore/app/exec/Main.hs:467]: This should write a shell script instead, so that after unpacking the bug report archive, we can run `./kore-exec.sh` and it will reproduce exactly what the user did.

File: kore/app/exec/Main.hs [hunk 2]
```diff
@@ -453,6 +701,19 @@ mainWithOptions execOptions = do
...
+    writeInReportDirectory :: FilePath -> IO ()
+    writeInReportDirectory tempDirectory = do
+        when . toReport . bugReport
+            <*> writeOptionsAndKoreFiles tempDirectory $ execOptions
+        Foldable.forM_ (outputFileName execOptions)
+            $ flip copyFile ("./" <> tempDirectory <> "/outputFile.kore")
+    archiveDirectoryReport :: FilePath -> IO ()
+    archiveDirectoryReport tempDirectory = do
+        directoryReportExists <- doesDirectoryExist tempDirectory
+        when directoryReportExists $ do
```
Comment (ttuegel) [inline kore/app/exec/Main.hs:713]:
```suggestion
    archiveDirectoryReport tempDirectory =
        Control.Monad.Extra.whenM (doesDirectoryExist tempDirectory) $ do
```

File: kore/app/exec/Main.hs [hunk 3]
```diff
@@ -403,14 +643,18 @@ main = do
 mainWithOptions :: KoreExecOptions -> IO ()
 mainWithOptions execOptions = do
     let KoreExecOptions { koreLogOptions } = execOptions
+    tempDirectory <- createTempDirectory "." "report"
```
Comment (ttuegel) [inline kore/app/exec/Main.hs:646]: Let's use [`withSystemTempDirectory`](https://hackage.haskell.org/package/temporary-1.3/docs/System-IO-Temp.html#v:withSystemTempDirectory) instead.

File: kore/app/exec/Main.hs [hunk 4]
```diff
@@ -423,9 +667,13 @@ mainWithOptions execOptions = do
...
         return $ ExitFailure 1
 
-    handleSomeException :: SomeException -> Main ExitCode
-    handleSomeException someException = do
+    handleSomeException :: FilePath -> SomeException -> Main ExitCode
+    handleSomeException tempDirectory someException = do
         errorException someException
+        lift
+            $ writeFile
+                (tempDirectory <> "/Errors.txt")
```
Comment (ttuegel) [inline kore/app/exec/Main.hs:675]:
```suggestion
                (tempDirectory <> "/error.log")
```

File: kore/src/Data/Limit.hs [hunk 5]
```diff
@@ -82,3 +83,7 @@ takeWithin :: (Enum a, Ord a) => Limit a -> [b] -> [b]
 takeWithin limit bs = zipWith const bs limiting
   where
     limiting = enumFromLimit limit (toEnum 1)
+
+maybeLimit :: b -> (a -> b) -> Limit a -> b
+maybeLimit b _ Unlimited = b
+maybeLimit _ f (Limit a) = f a
```
Comment (ttuegel) [inline kore/src/Data/Limit.hs:89]:
```suggestion
maybeLimit b f = foldr (\a _ -> f a) b
```

File: kore/src/Kore/Log.hs [hunk 6]
```diff
@@ -127,6 +138,22 @@ withMainLogger
...
+    :: FilePath
+    -> KoreLogOptions
+    -> (LogAction IO ActualEntry -> IO a)
+    -> IO a
+withMainReport
+    reportDirectory
+    koreLogOptions@KoreLogOptions { timestampsSwitch, exeName }
+    continue
+  =
+    Colog.withLogTextFile ("./" <> reportDirectory <> "/LoggedErrors.txt")
```
Comment (ttuegel) [inline kore/src/Kore/Log.hs:151]: `reportDirectory` should be an absolute filename.

```suggestion
    Colog.withLogTextFile (reportDirectory </> getExeName exeName <.> "log")
```

File: kore/src/Kore/Log.hs [hunk 7]
```diff
@@ -127,6 +138,22 @@ withMainLogger
...
+        $ continue
+        . koreLogTransformer koreLogOptions { logLevel = Error}
+        . koreLogFilters koreLogOptions { logLevel = Error}
```
Comment (ttuegel) [inline kore/src/Kore/Log.hs:154]: We should use the filters that the user applied. The user filters are applied in one place: `withMainLogger`, so this logger should be moved there.

File: test/include.mk [hunk 8]
```diff
@@ -155,5 +155,6 @@ golden: $(GOLDEN)
 
 clean:
 	rm -fr $(KOMPILED) $(TEST_DIR)/*.out $(TEST_DIR)/*.save-proofs.kore
+	rm -fr report*
```
Comment (ttuegel) [inline test/include.mk:158]:
```suggestion
```

File: kore/app/exec/Main.hs [hunk 9]
```diff
@@ -392,6 +445,193 @@ parserInfoModifiers =
...
+    , "--log-level " <> fmap Char.toLower (show logLevel)
+    , timestampsSwitchFlag timestampsSwitch
+    , logEntriesFlag logEntries
+    , debugSolverOptionsFlag debugSolverOptions
+    , logSQLiteOptionsFlag logSQLiteOptions
+    , if warningSwitch == AsError then "--warnings-to-errors" else ""
+    ]
+    <> debugApplyEquationOptionsFlag debugApplyEquationOptions
+    <> debugAttemptEquationOptionsFlag debugAttemptEquationOptions
+    <> debugEquationOptionsFlag debugEquationOptions
```
Comment (ttuegel) [inline kore/app/exec/Main.hs:474]: This needs a property test showing that we can parse the output. That test will be easier to write if this function returns a `[String]` equivalent to the list that would be returned by `getArgs`; that is: using separate list entries instead of spaces between arguments.

```suggestion
    concat
    [ koreLogTypeFlag logType
    , ["--log-level", fmap Char.toLower (show logLevel)]
    , timestampsSwitchFlag timestampsSwitch
    , logEntriesFlag logEntries
    , debugSolverOptionsFlag debugSolverOptions
    , logSQLiteOptionsFlag logSQLiteOptions
    , ["--warnings-to-errors" | AsError <- warningSwitch ]
    , debugApplyEquationOptionsFlag debugApplyEquationOptions
    , debugAttemptEquationOptionsFlag debugAttemptEquationOptions
    , debugEquationOptionsFlag debugEquationOptions
    ]
```

File: kore/app/exec/Main.hs [hunk 10]
```diff
@@ -348,15 +397,19 @@ parseKoreExecOptions =
...
-            , ("any-heating-cooling", heatingCooling priorityAnyStrategy)
-            , ("all-heating-cooling", heatingCooling priorityAllStrategy)
+            [ ("any", ("any", priorityAnyStrategy))
+            , ("all", ("all", priorityAllStrategy))
+            ,   ( "any-heating-cooling"
+                , ("any-heating-cooling", heatingCooling priorityAnyStrategy)
+                )
+            ,   ( "all-heating-cooling"
+                , ("all-heating-cooling", heatingCooling priorityAllStrategy)
+                )
```
[the remark this answers is not in the document]
Comment (andreiburdusa) [reply kore/app/exec/Main.hs:412]: It uses [`readSum`](https://github.com/kframework/kore/blob/master/kore/app/exec/Main.hs#L214) which discards the first component of the pair `(String, value)`, but we need it in order to recreate the flag.
I'll change `readSum` to not discard it anymore, but I'll change its call sites to ignore the extra value

File: kore/app/repl/Main.hs [hunk 11]
```diff
@@ -203,7 +203,7 @@ mainWithOptions
         , outputFile
         , koreLogOptions
         }
-  = withLogger koreLogOptions $ \actualLogAction -> do
+  = withLogger mempty koreLogOptions $ \actualLogAction -> do
```
Comment (ttuegel) [inline kore/app/repl/Main.hs:206]: Why are we using an empty `FilePath` here?

File: kore/test/Test/Kore/BugReport.hs [hunk 12]
```diff
@@ -0,0 +1,96 @@
...
+                    | level <- ["debug", "info", "warning", "error"]
+                ]
+        timestampsSwitch <- forAllFlags
+            [["--enable-log-timestamps"], ["--disable-log-timestamps"]]
+        logEntries <- forAll $ do
+            shuffled <- Gen.shuffle (fmap show entryTypeReps)
+            subseq <- Gen.subsequence shuffled
+            let values = [List.intercalate "," subseq]
+            return $ "--log-entries" : values
+            --[["--log-entries", entries] | entries <- getEntryTypesAsText]
```
Comment (ttuegel) [inline kore/test/Test/Kore/BugReport.hs:50]:
```suggestion
```

File: kore/test/Test/Kore/BugReport.hs [hunk 13]
```diff
@@ -0,0 +1,96 @@
...
+            debugEquationOptions = concat
+                [ ["--debug-equation", "eq" <> show index]
+                    | index <- [0..optionsNumber]
+                ]
+
+        let arguments = concat
+                [ logType, logLevel, timestampsSwitch, logEntries
+                    , debugSolverOptions, logSQLiteOptions, warningSwitch
+                    , debugApplyEquationOptions, debugAttemptEquationOptions
+                    , debugEquationOptions
```
Comment (ttuegel) [inline kore/test/Test/Kore/BugReport.hs:73]:
```suggestion
                , debugSolverOptions, logSQLiteOptions, warningSwitch
                , debugApplyEquationOptions, debugAttemptEquationOptions
                , debugEquationOptions
```

File: kore/app/exec/Main.hs [hunk 14]
```diff
@@ -453,6 +626,18 @@ mainWithOptions execOptions = do
...
+    writeInReportDirectory tempDirectory = do
+        when . isJust . toReport . bugReport
+            <*> writeOptionsAndKoreFiles tempDirectory $ execOptions
+        Foldable.forM_ (outputFileName execOptions)
+            $ flip copyFile (tempDirectory <> "/outputFile.kore")
+
+    archiveDirectoryReport :: FilePath -> FilePath -> IO ()
+    archiveDirectoryReport tempDirectory dest = do
+        files <- listDirectory tempDirectory
+        createTarGz (dest <> ".tar.gz") tempDirectory files
```
Comment (ttuegel) [inline kore/app/exec/Main.hs:639]: `listDirectory` seems to be used every time `createTarGz` is called; can we extract a helper function?

File: kore/app/exec/Main.hs [hunk 15]
```diff
@@ -402,16 +561,26 @@ main = do
...
+                $ handle handleWithConfiguration go
+            let KoreExecOptions { rtsStatistics } = execOptions
+            Foldable.forM_ rtsStatistics $ \filePath ->
+                writeStats filePath =<< getStats
+            let reportPath = maybe tempDirectory ("./" <>) (toReport bugReport)
+            writeInReportDirectory tempDirectory
+                `catch` \(_ ::SomeException) ->
+                    archiveDirectoryReport tempDirectory reportPath
+            archiveDirectoryReport tempDirectory reportPath
+            hPutStrLn stderr $ "\nCreated " <> reportPath <> ".tar.gz"
```
Comment (ttuegel) [inline kore/app/exec/Main.hs:582]: Let's move this into `archiveDirectoryReport`.

File: kore/app/repl/Main.hs [hunk 16]
```diff
@@ -203,49 +208,60 @@ mainWithOptions
...
+                        specDefIndexedModule
+                        Nothing
+                        mvarLogAction
+                        replScript
+                        replMode
+                        scriptModeOutput
+                        outputFile
+                        mainModuleName
+            files <- listDirectory tempDirectory
+            createTarGz (tempDirectory <> ".tar.gz") tempDirectory files
```
Comment (ttuegel) [inline kore/app/repl/Main.hs:264]: Let's extract `archiveDirectoryReport` from `kore-exec` so that we can use it here, too.

File: kore/app/exec/Main.hs [hunk 17]
```diff
@@ -402,16 +561,26 @@ main = do
...
+                $ handle handleSomeEntry
+                $ handle handleWithConfiguration go
+            let KoreExecOptions { rtsStatistics } = execOptions
+            Foldable.forM_ rtsStatistics $ \filePath ->
+                writeStats filePath =<< getStats
+            let reportPath = maybe tempDirectory ("./" <>) (toReport bugReport)
+            writeInReportDirectory tempDirectory
+                `catch` \(_ ::SomeException) ->
+                    archiveDirectoryReport tempDirectory reportPath
+            archiveDirectoryReport tempDirectory reportPath
```
Comment (ttuegel) [inline kore/app/exec/Main.hs:581]: This will call `archiveDirectoryReport` twice if there is an error. Let's try this instead:

```suggestion
            finally
                (writeInReportDirectory tempDirectory)
                (archiveDirectoryReport tempDirectory reportPath)
```
