### PR TITLE
Fix Ac Unification error and Add new integration test

### LINKED ISSUE #2378: Error unifying empty set with symbolic function applications
Error:
```
kore-exec: [275901] Error (ErrorException):
    Unification case that should be handled somewhere else: attempting normalized unification with a non-element-variable opaque term or non-function maps could lead to infinite loops.
      first=
        /* Fl Fn D Sfa */
        Lblkeys'LParUndsRParUnds'MAP'Unds'Set'Unds'Map{}(
            /* Fl Fn D Sfa */ ConfigVarM:SortMap{}
        )
      second=
        /* Fl Fn D Sfa Cl */ /* InternalSet: */ Lbl'Stop'Set{}()
    CallStack (from HasCallStack):
      error, called at src/Kore/Builtin/AssociativeCommutative.hs:1331:17 in kore-0.38.0.0-9AAldr6u5i39IiZl5oUbB8:Kore.Builtin.AssociativeCommutative
Created bug report: kore-exec.tar.gz
```

To reproduce:

tmp.k
```k
module TMP
  imports SET
  imports MAP

  syntax B  ::= b(Set)
            | "c"
  syntax KItem ::= B

  rule b(.Set) => c
  rule b(SetItem(_:KItem) S:Set) => b(S)

endmodule
```

tmp-proof.k
```k
module TMP-PROOF
  imports TMP

  claim b(keys(_M:Map)) => 0

endmodule
```

Command line:
```sh
kompile tmp.k --backend haskell && kprove tmp-proof.k
```

[kore-exec.tar.gz](https://github.com/kframework/kore/files/5894514/kore-exec.tar.gz)

### PR DESCRIPTION
**Pull request by MirceaS**
Fixes #2378 

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

File: kore/src/Kore/Builtin/AssociativeCommutative.hs [hunk 1]
```diff
@@ -803,13 +803,13 @@ unifyEqualsNormalizedAc
                             allElements1
                             allElements2
                             Nothing
-                ([opaque], []) ->
+                ([opaque@(ElemVar_ _)], []) ->
                     lift $
                         unifyEqualsElementLists'
```
Comment (ttuegel) [inline kore/src/Kore/Builtin/AssociativeCommutative.hs:808]: Since this function always fails when `opaque` is not an `ElemVar`, please change the type of `unifyEqualsElementLists'`.

File: kore/src/Kore/Builtin/AssociativeCommutative.hs [hunk 2]
```diff
@@ -803,13 +803,13 @@ unifyEqualsNormalizedAc
                             allElements1
                             allElements2
                             Nothing
-                ([opaque], []) ->
+                ([ElemVar_ opaque], []) ->
```
Comment (ttuegel) [inline kore/src/Kore/Builtin/AssociativeCommutative.hs:806]: We should combine these with the guarded cases, below.

File: kore/src/Kore/Builtin/AssociativeCommutative.hs [hunk 3]
```diff
@@ -1301,26 +1301,26 @@ unifyEqualsElementLists
...
+                _ ->
+                    error . show . Pretty.vsep $
+                        [ "Unification case that should be handled somewhere else: \
+                          \attempting normalized unification with \
+                          \non-function maps could lead to infinite loops."
+                        , Pretty.indent 2 "first="
+                        , Pretty.indent 4 (unparse first)
+                        , Pretty.indent 2 "second="
+                        , Pretty.indent 4 (unparse second)
+                        ]
```
Comment (ttuegel) [inline kore/src/Kore/Builtin/AssociativeCommutative.hs:1323]: Why is this still reachable?

File: kore/src/Kore/Builtin/Map.hs [hunk 4]
```diff
@@ -499,10 +499,9 @@ internalize ::
     TermLike variable ->
     TermLike variable
 internalize tools termLike
-    | fromMaybe False (isMapSort tools sort')
```
Comment (ttuegel) [inline kore/src/Kore/Builtin/Map.hs:502]: Are we just removing this check because it is redundant? Or is there another reason?

**Review by ttuegel — CHANGES_REQUESTED** [review]

File: kore/src/Kore/Builtin/Map.hs (hunk 4 above)
Comment (MirceaS) [reply kore/src/Kore/Builtin/Map.hs:502]: This is the check that I asked you about the other day, the one that Evan removed in [his PR](https://github.com/kframework/kore/pull/2440) that I then had to revert. You suggested I leave it in even if it doesn't solve the Issue linked to this PR.

File: kore/src/Kore/Builtin/AssociativeCommutative.hs (hunk 3 above)
Comment (MirceaS) [reply kore/src/Kore/Builtin/AssociativeCommutative.hs:1323]: `remainderTerm` may not be a function pattern and as the error message suggests, attempting normalized unification with non-function maps could lead to infinite loops.

File: kore/src/Kore/Builtin/Map.hs (hunk 4 above)
Comment (ttuegel) [reply kore/src/Kore/Builtin/Map.hs:502]: Oh, that is not the check I thought you were removing. It **is** redundant, and I'm glad to be rid of it, but it doesn't have anything to do with this issue in particular.

**Review by ttuegel — CHANGES_REQUESTED** [review]
Please update the title of the pull request following [these guidelines](https://runtimeverification.slack.com/archives/CC360GUTG/p1615342647121700).

File: kore/src/Kore/Builtin/Map.hs (hunk 4 above)
Comment (MirceaS) [reply kore/src/Kore/Builtin/Map.hs:502]: So, is it fine to leave it in this PR or should I open a new PR?

**Review by emarzion — APPROVED** [review]
