### PR TITLE
evalKEq: Give result for identical non contructor-like patterns

### LINKED ISSUE #2595: Failing to simplify equality
At the end of execution, I have the following in my path conditions:

```
#And
  {
    true          
  #Equals                                                                                                                                                                     
notBool ( Source:Address ~> . ) ==K ( Source:Address ~> . ) orBool ( ( KnownAddresses [ TokenAddress:Address ] ~> . ) ==K ( #Contract ( _A , T ) ~> . ) andBool notBool ( T:Type ~> . ) ==K ( pair .AnnotationList address .AnnotationList contract .AnnotationList nat .AnnotationList ~> . ) )
  }  
```

Basically I would want the second term of the `orBool` clause to be true (I think that would make my proof go through), and it seems clear the prover should be able to deduce that the first term is false. I don't know how I would even give it a further hint. Any ideas?

[bug-report-name.tar.gz](https://github.com/kframework/kore/files/6427555/bug-report-name.tar.gz)

### PR DESCRIPTION
**Pull request by andreiburdusa**
Fixes #2595 

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

File: kore/src/Kore/Builtin/KEqual.hs [hunk 1]
```diff
@@ -156,7 +156,9 @@ evalKEq ::
     simplifier (AttemptedAxiom variable)
 evalKEq true _ (valid :< app) =
     case applicationChildren of
-        [t1, t2] -> Builtin.getAttemptedAxiom (evalEq t1 t2)
+        [t1, t2]
+            | t1 == t2 -> Builtin.appliedFunction $ Bool.asPattern sort true
```
Comment (ttuegel) [inline kore/src/Kore/Builtin/KEqual.hs:160]: Can we move this guard into `evalEq`?

**Review by ttuegel — APPROVED** [review]
