### PR TITLE
Bug fix in Bool unification

### LINKED ISSUE #2695: Master branch fails KEVM proof-suite
On K master (* 72d33ae0e0 - Update dependency: haskell-backend/src/main/native/haskell-backend (#2016)), which is immediately after merging this PR: https://github.com/kframework/k/pull/2016

I have a proof that loops. This comes from KEVM, prior to this it takes about 25s for this proof to run, but now it times out with a time limit of 50min.

Here is the minimized example `test.k`:

```
requires "domains.md"

module EVM
    imports INT

    configuration
        <k> $PGM:EthereumSimulation </k>
    syntax EthereumSimulation

endmodule

module INFINITE-GAS
    imports EVM

    syntax Int ::= #gas ( Int ) [function, functional, no-evaluators, klabel(infGas), symbol, smtlib(infGas)]
 // ---------------------------------------------------------------------------------------------------------
    rule #gas(_) <Int I          => false requires I <=Int 1                                       [simplification]
    rule #gas(G) <Int I +Int I'  => false requires notBool (#gas(G) <Int I orBool #gas(G) <Int I') [simplification]

endmodule

module VERIFICATION
    imports INFINITE-GAS

    syntax KItem ::= runLemma ( Step ) | doneLemma ( Step )
 // -------------------------------------------------------
    rule <k> runLemma(S) => doneLemma(S) ... </k>

    syntax Step ::= Bool
 // --------------------

endmodule

module INFINITE-GAS-SPEC
    imports VERIFICATION

    claim <k> runLemma(#gas(GAVAIL) <Int log2Int(G0) +Int 1)  => doneLemma(false) ... </k> requires 0 <Int G0 andBool G0 <=Int 1

endmodule
```

To reproduce the looping behavior, run:

```
kompile --backend haskell test.k --main-module VERIFICATION --syntax-module VERIFICATION
timeout 120 kprove test.k --def-module VERIFICATION --spec-module INFINITE-GAS-SPEC
```

Note the 120s timeout here. If you remove either of the lemmas in `INFINITE-GAS-SPEC`, it fails very quickly (4s or so).

On KEVM master, the proof that inspired this minimized example (it's been mangled a bunch to minimize it) passes in about 25s.

### PR DESCRIPTION
**Pull request by MirceaS**
Fixes #2695 

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

**Comment by MirceaS** [comment]
The diff is not rendered very helpfully but what was happening was that we were calling some unification functions with the wrong term from the pair.

**Review by emarzion — APPROVED** [review]

File: kore/src/Kore/Step/Simplification/AndTerms.hs [hunk 1]
```diff
@@ -180,13 +180,13 @@ maybeTermEquals notSimplifier childTransformers first second = do
         | Just boolAndData <- Builtin.Bool.matchUnifyBoolAnd second first =
             lift $ Builtin.Bool.unifyBoolAnd childTransformers second boolAndData
         | Just boolOrData <- Builtin.Bool.matchUnifyBoolOr first second =
-            lift $ Builtin.Bool.unifyBoolOr childTransformers second boolOrData
-        | Just boolOrData <- Builtin.Bool.matchUnifyBoolOr second first =
             lift $ Builtin.Bool.unifyBoolOr childTransformers first boolOrData
+        | Just boolOrData <- Builtin.Bool.matchUnifyBoolOr second first =
+            lift $ Builtin.Bool.unifyBoolOr childTransformers second boolOrData
```
Comment (ttuegel) [inline kore/src/Kore/Step/Simplification/AndTerms.hs:185]: My comment here this morning was that we should modify `matchUnifyBoolOr` so that the required pattern (`first` or `second`) is included in `boolOrData`. That way, we don't have this coordination problem between `AndTerms` and `matchUnifyBoolOr`. But that is something @emarzion 's pull request.

Comment (emarzion) [reply kore/src/Kore/Step/Simplification/AndTerms.hs:185]: My pull request does handle this now (https://github.com/kframework/kore/blob/0503e7e35f64a80b3132e5641ea2dd4f024c57ff/kore/src/Kore/Step/Simplification/AndTerms.hs#L178) though `first, second` remain as arguments.  Should I place those in the records as well?

Comment (ana-pantilie) [reply kore/src/Kore/Step/Simplification/AndTerms.hs:185]: @emarzion What do those arguments represent?

Comment (emarzion) [reply kore/src/Kore/Step/Simplification/AndTerms.hs:185]: Those are the two terms being unified.

**Comment by MirceaS** [comment]
@ana-pantilie Do you have any idea why this might be failing?

**Comment by ana-pantilie** [comment]
> @ana-pantilie Do you have any idea why this might be failing?

Was it failing when you initially found the fix for the looping behavior?

**Comment by MirceaS** [comment]
@ana-pantilie Everett confirmed integration test expected behaviour

**Comment by ana-pantilie** [comment]
> @ana-pantilie Everett confirmed integration test expected behaviour

Cool, thanks for checking!

**Review by ana-pantilie — APPROVED** [review]
