### PR TITLE
Add a --no-bug-report option

### LINKED ISSUE #2180: Add a --no-bug-report option
`kore-exec --no-bug-report` would be useful for the test suite, to avoid littering.

### PR DESCRIPTION
**Pull request by emarzion**
Fixes #2180

- Makes `BugReport` into a wrapper for `FilePath`.
- Replaces `BugReport` with `BugReportOption`, a sum type with three constructors:
  - `BugReportEnable`, which accepts a `BugReport` argument, representing the option where a bug report is always created in the corresponding filepath.
  - `BugReportDisable`, representing the option where a bug report is never created.
  - `BugReportOnError`, representing the option where a bug report is only created in `kore-exec.tar.gz` when the program crashes.
- Replaces `parseBugReport` with `parseBugReportOption`.
  - The flag `--bug-report REPORT_FILE` parses to `BugReportEnable (BugReport REPORT_FILE)`.
  - The flag `--no-bug-report` parses to `BugReportDisable`.
  - `BugReportOnError` is the default.
- Updates `withBugReport` to take a `BugReportOption` argument in place of a `BugReport` option, implementing the corresponding logic.
- Replaces `bugReport` with `bugReportOption` in `KoreExecOptions`.
- Updates the calls to `withBugReport` in `exec/Main.hs` and `repl/Main.hs`.
---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

**Review by ttuegel — CHANGES_REQUESTED** [review]
This looks good, the only significant change I requested is to change the name of `BugReportDefault`.

**Review by ttuegel — CHANGES_REQUESTED** [review]
Sorry, one more thing: please add unit tests for `parseBugReportOption`.

File: kore/test/Test/Kore/BugReport.hs [hunk 1]
```diff
@@ -82,6 +90,40 @@ test_parse =
...
+            []
+            BugReportOnError
+
+    assertParse :: [String] -> BugReportOption -> Assertion
+    assertParse arguments opt =
+        assertEqual
+            (  "Encountered error when parsing flag\n  "
+            ++ unwords arguments
+            ++ "\n."
+            )
```
Comment (ttuegel) [inline kore/test/Test/Kore/BugReport.hs:123]: I want to change the message when the test fails. I think it is misleading because it suggests an error occurred while running the test, which may not be the case. I would also like to use the facilities in `Pretty` and `Debug` (in our library) to print the message:

```suggestion
            (show $ Pretty.vsep
                [ "while parsing:"
                , Pretty.indent 4 (debug arguments)
                , "expected:"
                , Pretty.indent 4 (debug opt)
                ]
            )
```

You would need to add

```.hs
import qualified Pretty
import Debug
```

above.

File: kore/test/Test/Kore/BugReport.hs [hunk 2]
```diff
@@ -10,6 +11,12 @@ import Hedgehog
 import qualified Hedgehog.Gen as Gen
 import qualified Hedgehog.Range as Range
 
+import Kore.BugReport
+    ( BugReport (..)
+    , BugReportOption (..)
+    , parseBugReportOption
+    )
+
```
Comment (ttuegel) [inline kore/test/Test/Kore/BugReport.hs:19]:
```suggestion
```

File: kore/test/Test/Kore/BugReport.hs [hunk 3]
```diff
@@ -82,6 +90,40 @@ test_parse =
...
+        assertParse
+            ["--no-bug-report"]
+            BugReportDisable
+
+    onErrorAssert =
+        assertParse
+            []
+            BugReportOnError
+
+    assertParse :: [String] -> BugReportOption -> Assertion
```
Comment (ttuegel) [inline kore/test/Test/Kore/BugReport.hs:117]: Using `HasCallStack` will ensure that failing tests are attributed to the right line number:

```suggestion
    assertParse :: HasCallStack => [String] -> BugReportOption -> Assertion
```

File: kore/test/Test/Kore/BugReport.hs [hunk 4]
```diff
@@ -82,6 +90,40 @@ test_parse =
             actual = expect >>= parseKoreLogOpts . unparseKoreLogOptions
         getParseResult expect === getParseResult actual
 
+test_bugReportOption :: TestTree
+test_bugReportOption =
+    testGroup
+        "Parse BugReportOption"
```
Comment (ttuegel) [inline kore/test/Test/Kore/BugReport.hs:96]: Our test discovery tool will name the test group correctly if you do this instead:

```suggestion
test_Parse_BugReportOption :: [TestTree]
test_Parse_BugReportOption =
```

File: kore/test/Test/Kore/BugReport.hs [hunk 5]
```diff
@@ -82,6 +90,40 @@ test_parse =
...
+        [ testCase "Parse BugReportEnable" enableAssert
+        , testCase "Parse BugReportDisable" disableAssert
+        , testCase "Parse BugReportOnError" onErrorAssert
```
Comment (ttuegel) [inline kore/test/Test/Kore/BugReport.hs:99]: I suggest adding a function to the `where` clause,

```.hs
test :: TestName -> [String] -> BugReportOption -> TestTree
test testName arguments opt =
    testCase testName $ assertParse arguments opt
```

Then the test cases can be written as:

```suggestion
        , test "Parse BugReportOnError" [] BugReportOnError
```

This way, it's easy to scan the list of test cases and we don't have to add `HasCallStack` to `enableAssert`, `disableAssert`, and `onErrorAssert`.

**Review by ttuegel — APPROVED** [review]

**Comment by ttuegel** [comment]
Please take care of my suggestions, but I already approved because I don't need to look at it again after.
