### PR TITLE
Reset the SMT solver at fixed intervals

### LINKED ISSUE #2125: Reset the SMT solver at fixed intervals
Follow-up: #2087 

Restarting the SMT solver at the start of each proof step is not sufficient if there are deeply-recursive symbolic function calls. The encapsulation of the SMT interface is also slightly broken by the need to call `reset` from the reachability proof module.

Instead, the SMT solver interface should keep an internal counter of the number of calls to `withSolver`. After that number exceeds some limit, the solver should reset itself (at the end of a call to `withSolver`, when we are guaranteed that the solver is not in use).

### PR DESCRIPTION
**Pull request by MirceaS**
---
Fixes #2125 
###### Reviewer checklist

- [ ] Test coverage: `stack test --coverage`
- [ ] Public API documentation: `stack haddock`

### CODE REVIEW

File: kore/src/SMT.hs [hunk 1]
```diff
@@ -321,14 +324,22 @@ instance MonadSMT SMT where
...
+                        counter
                     )
                     (Trans.liftIO $ pop solver)
-                )
+            SMT $ State.modify (+ 1)
+            counterNew <- SMT State.get
+            -- Due to an issue with the SMT solver, we need to
+            -- reinitialise it after a number of runs, specified here.
+            -- This number can be adjusted based on experimentation
+            when (counterNew >= 100) reinit
```
Comment (ttuegel) [inline kore/src/SMT.hs:341]:
```suggestion
            when (counterNew >= 100) $ (SMT . RWST) $ \ _ _ ->
                    runRWST
                        (getSMT reinit)
                        (SolverInitAndHandle userInit mvar config)
                        counter
```

**Comment by MirceaS** [comment]
Note: The code currently assumes that `smt` is well behaved in the sense that it puts back the shared variable so that the potential `reinit` doesn't block

**Review by ttuegel — CHANGES_REQUESTED** [review]
I requested some changes, but I'm going to take care of them right now as part of my clean-up because I think we need it for #2170.

**Review by ttuegel — APPROVED** [review]
