### PR TITLE
NormalizedAc.concreteElements, InternalMap, InternalSet: use HashMap and HashSet

### LINKED ISSUE #2508: KEVM semantics Haskell backend performance regression
A commit which updates the Haskell backend (https://github.com/kframework/k/pull/1830) causes the `hkg/totalSupply-spec.k` proof on KEVM to go from about 100s to 170s on my machine. This is affecting other proofs as well.

```
* 42c0b1531 - !!! (44976006) deps/k: 449760069 - Update dependency: haskell-backend/src/main/native/haskell-backend (#1830)
| testset: prove-smoke - Fri Mar 26 20:49:15 UTC 2021
| 0  0.60s    0.02s     0.55s     3348KB     rm    -rf                                             deps                           .build
| 0  1.47s    0.95s     0.54s     58616KB    git   submodule                                       update                         --init        --recursive
| 0  246.42s  2048.49s  2347.27s  3059360KB  make  deps                                            RELEASE=true
| 0  31.26s   207.96s   6.54s     2728340KB  make  build-haskell                                   -j8                            RELEASE=true
| 0  166.89s  352.96s   8.22s     3854948KB  make  tests/specs/erc20/hkg/totalSupply-spec.k.prove  TEST_SYMBOLIC_BACKEND=haskell
| 
* 8842ac60b - !!! (4a180596) deps/k: 4a180596e - nix: Add ncurses to runtime dependencies for tput (#1871)
| testset: prove-smoke - Fri Mar 26 20:41:48 UTC 2021
| 0  0.54s    0.00s     0.52s     3184KB     rm    -rf                                             deps                           .build
| 0  1.46s    0.95s     0.55s     66596KB    git   submodule                                       update                         --init        --recursive
| 0  236.13s  2011.09s  2101.76s  2801192KB  make  deps                                            RELEASE=true
| 0  30.18s   202.95s   6.90s     2783132KB  make  build-haskell                                   -j8                            RELEASE=true
| 0  98.84s   260.68s   7.08s     3411720KB  make  tests/specs/erc20/hkg/totalSupply-spec.k.prove  TEST_SYMBOLIC_BACKEND=haskell
```

Reproduction steps (in KEVM repo against _update-deps_kframework_k branch - https://github.com/kframework/evm-semantics/pull/980):

```
make deps RELEASE=true
make build-haskell -j8 RELEASE=true
make tests/specs/hkg/totalSupply-spec.k.prove TEST_SYMBOLIC_BACKEND=haskell KPROVE_OPTS=--bug-report
```

I've attached the input kore file for the proof (generated with KEVM set to latest K), which shows the same performance issue.
[kevm-bug-totalSupply.tar.gz](https://github.com/kframework/kore/files/6214456/kevm-bug-totalSupply.tar.gz)

### PR DESCRIPTION
**Pull request by ana-pantilie**
Fixes #2508

Recent changes to the backend resulted in more frequent AC collection comparisons and this PR should fix the performance of that.

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

**Comment by ana-pantilie** [comment]
Test SET.set2list is set2list:

```
Except:
\and{List{}}(
    /* term: */
    /* Fl Fn D Sfa Cl */
    /* InternalList: */ concatList{}(
        elementList{}(/* Fl Fn D Sfa Cl */ \dv{Int{}}("-940")),
        elementList{}(/* Fl Fn D Sfa Cl */ \dv{Int{}}("-876"))
    ),
\and{List{}}(
    /* predicate: */
    /* D Sfa */ \top{List{}}(),
    /* substitution: */
    \top{List{}}()
))
Actual:
\and{List{}}(
    /* term: */
    /* Fl Fn D Sfa Cl */
    /* InternalList: */ concatList{}(
        elementList{}(/* Fl Fn D Sfa Cl */ \dv{Int{}}("-876")),
        elementList{}(/* Fl Fn D Sfa Cl */ \dv{Int{}}("-940"))
    ),
\and{List{}}(
    /* predicate: */
    /* D Sfa */ \top{List{}}(),
    /* substitution: */
    \top{List{}}()
))
```

**Comment by ana-pantilie** [comment]
I noticed that some of the property tests were actually failing because the term contained symbolic elements which were reordered. Turns out I had modified part of `Kore.Builtin.AssociativeCommutative` to use `HashMap` instead of `Map`, and we reuse the same functions for the symbolic parts and the concrete parts. Fixing this meant switching back to using `Map` throughout that module, and at the end converting the concrete `Map`s to `HashMap`s.

Other issues are related to our builtin evaluation and tests: we use `Map` and `Set` there, so we end up with two representations which differ by the ordering of the elements. 

Would a good solution be to switch everything related to maps and sets to use `HashMap` and `HashSet` instead? I think that mixing the regular and hashed versions is pretty confusing and it's probably not that ideal in terms of performance, but I might be wrong or overlooking something.

Sort of related: do we still want to keep the symbolic elements and the opaque elements in lists?

**Comment by ana-pantilie** [comment]
We decided to use the hashed versions instead everywhere in the builtin code.

**Comment by ana-pantilie** [comment]
Integration test failure:

```
module VERIFICATION
  imports PATH

endmodule

module ONE-PATH-B-SPEC
  imports VERIFICATION
  imports PATH

  // This should be provable as an one-path claim, but should not be provable as an 
  //all-path claim.
  claim <k> select => b </k>
       <state> SetItem(b) SetItem(c) </state>
    [one-path]

endmodule
```

with semantics:
```
module PATH
  import BOOL
  import INT
  import SET
  syntax S ::= "a" | "b" | "c" 
  syntax Cmd ::= "select"

  configuration <k> .K </k> <state> .Set </state>

  rule <k> select => X ...</k> <state>... SetItem(X:S) ...</state>
endmodule
```

Expected result is `\\top`, but with these changes it's:
```
<generatedTop>
  <k>
    c ~> .
  </k>
  <state>
    SetItem ( b )
    SetItem ( c )
  </state>
</generatedTop>
```

**Comment by ana-pantilie** [comment]
`Set.test_toList` runs which consistently fail:
```

Initial pattern:
/* Fl Fn D Sfa Cl */
/* InternalSet: */ concatSet{}(
    /* concrete element: */ elementSet{}(\dv{Int{}}("-744")),
    /* concrete element: */ elementSet{}(\dv{Int{}}("-680"))
)
Expected:
\and{List{}}(
    /* term: */
    /* Fl Fn D Sfa Cl */
    /* InternalList: */ concatList{}(
        elementList{}(/* Fl Fn D Sfa Cl */ \dv{Int{}}("-680")),
        elementList{}(/* Fl Fn D Sfa Cl */ \dv{Int{}}("-744"))
    ),
\and{List{}}(
    /* predicate: */
    /* D Sfa */ \top{List{}}(),
    /* substitution: */
    \top{List{}}()
))
Actual:
\and{List{}}(
    /* term: */
    /* Fl Fn D Sfa Cl */
    /* InternalList: */ concatList{}(
        elementList{}(/* Fl Fn D Sfa Cl */ \dv{Int{}}("-744")),
        elementList{}(/* Fl Fn D Sfa Cl */ \dv{Int{}}("-680"))
    ),
\and{List{}}(
    /* predicate: */
    /* D Sfa */ \top{List{}}(),
    /* substitution: */
    \top{List{}}()
))

-------------------------------------------------------
Initial pattern:
/* Fl Fn D Sfa Cl */
/* InternalSet: */ concatSet{}(
    /* concrete element: */ elementSet{}(\dv{Int{}}("-1000")),
    /* concrete element: */ elementSet{}(\dv{Int{}}("-936"))
)
Expected:
\and{List{}}(
    /* term: */
    /* Fl Fn D Sfa Cl */
    /* InternalList: */ concatList{}(
        elementList{}(/* Fl Fn D Sfa Cl */ \dv{Int{}}("-936")),
        elementList{}(/* Fl Fn D Sfa Cl */ \dv{Int{}}("-1000"))
    ),
\and{List{}}(
    /* predicate: */
    /* D Sfa */ \top{List{}}(),
    /* substitution: */
    \top{List{}}()
))
Actual:
\and{List{}}(
    /* term: */
    /* Fl Fn D Sfa Cl */
    /* InternalList: */ concatList{}(
        elementList{}(/* Fl Fn D Sfa Cl */ \dv{Int{}}("-1000")),
        elementList{}(/* Fl Fn D Sfa Cl */ \dv{Int{}}("-936"))
    ),
\and{List{}}(
    /* predicate: */
    /* D Sfa */ \top{List{}}(),
    /* substitution: */
    \top{List{}}()
))
```

File: kore/test/Test/Kore/Builtin/Set.hs [hunk 1]
```diff
@@ -67,16 +67,18 @@ import qualified Data.Default as Default
...
 import qualified Data.Maybe as Maybe (
     fromJust,
  )
 import qualified Data.Sequence as Seq
-import Data.Set (
-    Set,
- )
-import qualified Data.Set as Set
+
+-- import qualified Data.Sequence as Seq
```
Comment (ana-pantilie) [inline kore/test/Test/Kore/Builtin/Set.hs:81]:
```suggestion
```

File: kore/test/Test/Kore/Builtin/Set.hs [hunk 2]
```diff
@@ -515,25 +522,33 @@ test_toList =
     testPropertyWithSolver
         "SET.set2list is set2list"
```
Comment (ana-pantilie) [inline kore/test/Test/Kore/Builtin/Set.hs:521]:
```suggestion
        "SET.set2list is implemented as a Haskell set to list transformation"
```

File: kore/test/Test/Kore/Builtin/Map.hs [hunk 3]
```diff
@@ -1580,3 +1585,15 @@ distinctVariables variables =
...
+
+-- | Utility function for mapping over the keys of a 'HashMap'.
+mapKeys ::
+    Hashable k2 =>
+    Eq k2 =>
+    (k1 -> k2) ->
+    HashMap k1 v ->
+    HashMap k2 v
+mapKeys f =
+    HashMap.fromList
```
Comment (MirceaS) [inline kore/test/Test/Kore/Builtin/Map.hs:1597]: Can you confirm that no use of this function supplies an `f` that is non-injective? Because if it did, we would risk losing entries from the hash map.

Comment (ana-pantilie) [reply kore/test/Test/Kore/Builtin/Map.hs:1597]: We only ever use this function in places where we used to use `Data.Map.Strict.mapKeys`, which has the same behavior you described.

**Review by MirceaS — APPROVED** [review]

**Review by andreiburdusa — APPROVED** [review]
