### PR TITLE
Throw an error when \not(\ceil(_)) appears in a stuck configuration

### LINKED ISSUE #2059: Throw an error when \not(\ceil(_)) appears in a stuck configuration
This is always a bug in the backend and we should prompt the user to file a bug report.

### PR DESCRIPTION
**Pull request by andreiburdusa**
---
Fixes #2059 
###### Reviewer checklist

- [ ] Test coverage: `stack test --coverage`
- [ ] Public API documentation: `stack haddock`

### CODE REVIEW

File: kore/src/Kore/Strategies/Verification.hs [hunk 1]
```diff
@@ -377,19 +391,33 @@ transitionRule'
...
+    Foldable.for_ (extractGoalStuck proofState) (\rule -> do
+        let resultPatternPredicate = predicate (getConfiguration rule)
+            multiAndPredicate = getMultiAndPredicate resultPatternPredicate
+        when (any (isNot_Ceil_ . unwrapPredicate) multiAndPredicate) $
+            error . show . Pretty.vsep $
+                [ "Found '\\not(\\ceil(_))' in stuck configuration:"
+                , Pretty.pretty rule
+                , "Please file a bug report."
+                ]
+        )
```
Comment (ttuegel) [inline kore/src/Kore/Strategies/Verification.hs:404]: Let's extract this to a helper function and include it as one of the transformers below. Be sure to check the _output_ of `transitionRule` and not the input.
