### PR TITLE
Use Makefile for generating regression tests

### LINKED ISSUE #2538: Update regression test script to use evm-semantics Makefile
[This script](https://github.com/kframework/kore/blob/master/scripts/generate-regression-tests.sh) should be updated to use the evm-semantics Makefile so that it gets changes that are made upstream.

### PR DESCRIPTION
**Pull request by ana-pantilie**
Fixes #2538

`scripts/generate-regression-tests.sh` now uses each project's Makefile to run the frontend for our regression tests.

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

**Review by dopamane — APPROVED** [review]

File: scripts/generate-regression-tests.sh [hunk 1]
```diff
@@ -7,7 +7,18 @@ kollect() {
...
-    "$@" --save-temps --dry-run | xargs $KORE/scripts/kollect.sh "$name" >> "$name.sh"
+    "$@" | xargs $KORE/scripts/kollect.sh "$name" >> "$name.sh"
+    chmod +x "$name.sh"
+}
+
+kollect-file() {
+    local name="$1"
+    local path="$2"
+    shift
+    shift
```
Comment (andreiburdusa) [inline scripts/generate-regression-tests.sh:18]: Why did you use `shift` here?
Could this two calls be replaced with one `shift 2` call?

Comment (ana-pantilie) [reply scripts/generate-regression-tests.sh:18]: `kollect-file` works similarly to `kollect`, but it also takes the output file path as an argument, and we need to shift past that argument now as well. You're right that it can be replaced with `shift 2`.

**Review by andreiburdusa — APPROVED** [review]
