### PR TITLE
Log the configuration for the strategy primitives that could fail.

### LINKED ISSUE #950: Output configuration even if there is an error
`kore-exec` should output the current configuration (or the disjunction of "live" configurations, if proving) even if there is an error to facilitate debugging. This probably will involve refactoring `kore-exec` so we can `bracket` the execution and collect errors.

### PR DESCRIPTION
**Pull request by virgil-serbanuta**
Fixes #950 

---

###### Reviewer checklist

- [ ] Test coverage: `stack test --coverage`
- [ ] Public API documentation: `stack haddock`

### CODE REVIEW

File: kore/src/Kore/Logger/ErrorBracket.hs [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+    {-# INLINE withErrorMessage #-}
+
+instance (Monoid w, ErrorBracket m) => ErrorBracket (AccumT w m) where
+    withErrorMessage message action =
+        AccumT
+        $ \w -> withErrorMessage message (runAccumT action w)
+    {-# INLINE withErrorMessage #-}
+
+instance ErrorBracket IO where
+    withErrorMessage message action =
```
Comment (ttuegel) [inline kore/src/Kore/Logger/ErrorBracket.hs]: We can implement this using [`onException`](https://hackage.haskell.org/package/exceptions-0.10.3/docs/Control-Monad-Catch.html#v:onException) from `Control.Monad.Catch` using the `MonadCatch` class instead of adding a new class.

File: kore/src/Kore/Logger/ErrorBracket.hs [hunk 2]
```diff
@@ -0,0 +1,100 @@
...
+    ( ListT
+    , mapListT
+    )
+
+class Monad m => ErrorBracket m where
+    withErrorMessage :: HasCallStack => Text -> m a -> m a
+
+instance ErrorBracket m => ErrorBracket (Strict.StateT s m) where
+    withErrorMessage message action =
+        Strict.StateT
```
Comment (ttuegel) [inline kore/src/Kore/Logger/ErrorBracket.hs]: This is `Control.Monad.Morph.hoist (withErrorMessage message)`, and so are most of the instances below, but see my comment about `MonadCatch`.

File: kore/src/Kore/Step/Simplification/Simplify.hs [hunk 3]
```diff
@@ -111,7 +114,7 @@ type SimplifierVariable variable = SubstitutionVariable variable
 type TermSimplifier variable m =
     TermLike variable -> TermLike variable -> m (Pattern variable)
 
-class (WithLog LogMessage m, MonadSMT m, MonadProfiler m)
+class (WithLog LogMessage m, MonadSMT m, MonadProfiler m, ErrorBracket m)
```
[the remark this answers is not in the document]
Comment (virgil-serbanuta) [reply kore/src/Kore/Step/Simplification/Simplify.hs]: Fixed.

File: kore/src/Kore/Strategies/Goal.hs [hunk 4]
```diff
@@ -486,12 +490,16 @@ removeDestination
     => Coercible goal (RulePattern variable)
     => goal
     -> Strategy.TransitionT (Rule goal) m goal
-removeDestination goal = do
-    let destination = getDestination goal
-        configuration = getConfiguration goal
-        removal = removalPredicate destination configuration
+removeDestination goal = errorBracket $ do
```
[the remark this answers is not in the document]
Comment (virgil-serbanuta) [reply kore/src/Kore/Strategies/Goal.hs]: Done.

File: kore/src/Kore/Logger/ErrorBracket.hs (hunk 1 above)
Comment (virgil-serbanuta) [reply kore/src/Kore/Logger/ErrorBracket.hs]: Done.

File: kore/src/Kore/Logger/ErrorBracket.hs (hunk 2 above)
Comment (virgil-serbanuta) [reply kore/src/Kore/Logger/ErrorBracket.hs]: Switched to MonadCatch
