### PR TITLE
Clarify final configuration

### LINKED ISSUE #2786: Function in the main condition not (re-)evaluated when the main condition changes
I think that there are two issues with the proof below, the title of the issue contains the first one that is encountered when debugging. The other issue is that rewriting stops at a random point for no apparent reason.

To reproduce:
----------------

Kore version 0.51.0.0
Git:
  revision:     0521b0ea0ca6c2f61192822edf45a2ace7a52310
  branch:       master
  last commit:  Thu Aug 5 08:10:21 2021 -0600

The `--bug-report` file: [condition-reevaluation.tar.gz](https://github.com/kframework/kore/files/6942463/condition-reevaluation.tar.gz)

Also:

tmp.k:
```
module TMP
  imports BOOL
  imports INT

  syntax ExpressionList ::= "nil" | cons(KItem, ExpressionList)

  syntax Bool ::= listElementsAreDistinct(ExpressionList)  [function, functional]
  
  rule listElementsAreDistinct(nil) => true
  rule listElementsAreDistinct(cons(E:KItem, Es:ExpressionList))
      => true
          andBool notBool #listContains(Es, E)
          andBool listElementsAreDistinct(Es)

  syntax Bool ::= #listContains(ExpressionList, KItem)  [function, functional]

  rule  #listContains(nil, _) => false
  rule  #listContains(cons(E:KItem, _:ExpressionList), E) => true
  rule  #listContains(cons(_:KItem, Es:ExpressionList), X:KItem)
          => #listContains(Es, X)  [owise]

  syntax KItem ::= lemmaLastDistinct(KItem, KItem, ExpressionList)

  rule lemmaLastDistinct(E1:KItem, E2:KItem, nil) => concretizeValue(E1 ==K E2)
  rule lemmaLastDistinct(E:KItem, E1:KItem, cons(E2:KItem, Es:ExpressionList))
      =>  concretizeValue(E ==K E2)
          ~> concretizeValue(E ==K E1)
          ~> concretizeValue(E1 ==K E2)
          ~> lemmaLastDistinct(E, E2, Es)

  syntax KItem ::= concretizeValue(KItem)
  rule concretizeValue(false) => .K  [label(concretizeValueFalse)]
  rule concretizeValue(true) => .K  [label(concretizeValueTrue)]

  syntax KItem ::= #last(KItem, ExpressionList)  [function, functional]
  syntax KItem ::= #last0(ExpressionList)  [function, functional]

  rule #last(E:KItem, nil) => E
  rule #last(_:KItem, Es:ExpressionList) => #last0(Es)
    requires pListLen(Es) >Int 0

  rule #last0(cons(E:KItem, Es:ExpressionList)) => #last(E, Es)

  syntax Int ::= pListLen(ExpressionList)  [function, functional, smtlib(pListLen)]
  rule pListLen(nil) => 0
  rule pListLen(cons(_:KItem, Es:ExpressionList)) => 1 +Int pListLen(Es)

endmodule
```

tmp-proof.k:
```
module TMP-PROOF
  imports TMP

  claim lemmaLastDistinct(E1, E2, Es) => .K
      requires listElementsAreDistinct(cons(E1, cons(E2, Es)))
      ensures E1 =/=K #last(E2, Es)

endmodule
```

Command line:
```
kompile tmp.k --backend haskell && kprove tmp-proof.k
```

The problem:
-----------------

The command line above produces the output below. There are two issues here:
* In the predicate, `#listContains ( cons ( E3 , nil ) , E2 )` is not evaluated, although the predicate also contains `#Not ( { E2 #Equals E3 } )`, which should be enough to allow it to be evaluated. Note that the `#Not ( { E2 #Equals E3 } )` part of the condition appeared during rewriting, when the configuration was split by `concretizeValue`. Similarly, `#listContains ( cons ( E2 , cons ( E3 , nil ) ) , E3 )` is not evaluated, although there is enough information to evaluate it.
* The prover thinks that this is the final configuration, although it should attempt to still rewrite `concretizeValue ( true )`

```
kore-exec: [985441] Warning (WarnClaimRHSIsBottom):
    (InfoReachability) while checking the implication:
    The right-hand side of the claim is bottom: /mnt/data/runtime-verification/elrond-multisig/tmp/tmp-proof.k:4:9-6:36
kore-exec: [986977] Warning (WarnStuckClaimState):
    (InfoReachability) while checking the implication:
    The proof has reached the final configuration, but the claimed implication is not valid. Location: /mnt/data/runtime-verification/elrond-multisig/tmp/tmp-proof.k:4:9-6:36
  #Not ( {
    E2
  #Equals
    E3
  } )
#And
  <k>
    concretizeValue ( true ) ~> _DotVar1 ~> .
  </k>
#And
  {
    false
  #Equals
    #listContains ( cons ( E2 , cons ( E3 , nil ) ) , E3 )
  }
#And
  {
    false
  #Equals
    #listContains ( cons ( E3 , nil ) , E2 )
  }
```

Information for myself: this was minimized from `protocol-correctness/proof/lemmas/list/contains/proof-last-distinct.k`

### PR DESCRIPTION
**Pull request by andreiburdusa**
Use `Transition.ifte` like [here](https://github.com/kframework/kore/blob/98e241ede419e7a9e1266393104fcbd84fb796e4/kore/src/Kore/Reachability/Claim.hs#L317) to turn empty transitions into `Proven`. Part of #2786 

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

File: kore/src/Kore/Reachability/Claim.hs [hunk 1]
```diff
@@ -334,9 +334,11 @@ transitionRule claims axiomGroups = transitionRuleWorker
             >>= return . applyResultToClaimState
```
Comment (ana-pantilie) [inline kore/src/Kore/Reachability/Claim.hs:334]: We probably want to do the same here, for claims. Can you give this a try as well?

File: kore/test/Test/Kore/Reachability/Prove.hs [hunk 2]
```diff
@@ -731,6 +736,20 @@ test_proveClaims =
          in [ mkTest "OnePath" simpleOnePathClaim
             , mkTest "AllPath" simpleAllPathClaim
             ]
+    , testCase "transitionRule: LHS is undefined" $ do
```
Comment (ana-pantilie) [inline kore/test/Test/Kore/Reachability/Prove.hs:739]: Let's move this to a separate group of tests, like `test_transitionRule`.

File: kore/test/Test/Kore/Reachability/Prove.hs [hunk 3]
```diff
@@ -733,6 +739,40 @@ test_proveClaims =
             ]
     ]
 
+test_transitionRule :: TestTree
+test_transitionRule =
+    testGroup
+        "transitionRule: AllPath"
+        [ testCase "ApplyAxioms: LHS is undefined" $ do
+            let claim :: AllPathClaim
+                claim = AllPathClaim $ simpleClaim (mkBottom Mock.testSort) Mock.a
```
Comment (ana-pantilie) [inline kore/test/Test/Kore/Reachability/Prove.hs:748]: I think we can factor this out.

File: kore/test/Test/Kore/Reachability/Prove.hs [hunk 4]
```diff
@@ -733,6 +739,40 @@ test_proveClaims =
...
+            actual <-
+                runSimplifierSMT Mock.env . runTransitionT $
+                    transitionRule
+                        []
+                        [[]]
+                        ApplyAxioms
+                        (Claimed claim)
```
Comment (ana-pantilie) [inline kore/test/Test/Kore/Reachability/Prove.hs:755]: I think we can factor this out.

**Review by ana-pantilie — APPROVED** [review]
I had a couple of clean-up requests, but otherwise looks good!
