### PR TITLE
Error on defining constructor for hooked sorts

### LINKED ISSUE #695: INT.add not applicable to declared constructor
The hooked symbol `INT.add` is not applied to concrete inputs when the user declares constructors in the builtin `Int` sort. We should reject constructors defined in hooked sorts, unless they are hooked to a known constructor symbol.

### Instructions

```
$ git clone https://github.com/kframework/k

$ cd k; mvn package -DskipTests -Dllvm.backend.skip -Dhaskell.backend.skip

$ cd k-distribution/tests/regression-new

$ make KOMPILE_BACKEND=haskell -C concrete-function/ --keep-going 2.a
make: Entering directory '/home/ttuegel/k/k-distribution/tests/regression-new/concrete-function'
cat 2.a.in 2>/dev/null | /home/ttuegel/k/k-distribution/bin/krun 2.a   -d . | diff - 2.a.out
Reading the input file TimeSpec {sec = 0, nsec = 49219}
Parsing the file TimeSpec {sec = 0, nsec = 162506487}
Verifying the definition TimeSpec {sec = 0, nsec = 147256802}
Reading the input file TimeSpec {sec = 0, nsec = 53089}
Parsing the file TimeSpec {sec = 0, nsec = 121147}
Verifying the pattern TimeSpec {sec = 0, nsec = 175905}
kore-exec: Expecting hook INT.add to reduce concrete pattern
        TermLike {getTermLike = CofreeT (Identity (Pattern {patternSort = SortActualSort (SortActual {sortActualName = Id {getId = "SortInt", idLocation = AstLocationFile (FileLocation {fileName = "/home/ttuegel/k/k-distribution/tests/regression-new/concrete-function/././a-kompiled/definition.kore", line = 224, column = 66})}, sortActualSorts = []}), freeVariables = fromList []} :< ApplicationF (Application {applicationSymbolOrAlias = SymbolOrAlias {symbolOrAliasConstructor = Id {getId = "Lbl'UndsPlus'Int'Unds'", idLocation = AstLocationFile (FileLocation {fileName = "/home/ttuegel/k/k-distribution/tests/regression-new/concrete-function/././a-kompiled/definition.kore", line = 3749, column = 9})}, symbolOrAliasParams = []}, applicationChildren = [CofreeT (Identity (Pattern {patternSort = SortActualSort (SortActual {sortActualName = Id {getId = "SortInt", idLocation = AstLocationFile (FileLocation {fileName = "/home/ttuegel/k/k-distribution/tests/regression-new/concrete-function/././a-kompiled/definition.kore", line = 364, column = 65})}, sortActualSorts = []}), freeVariables = fromList []} :< ApplicationF (Application {applicationSymbolOrAlias = SymbolOrAlias {symbolOrAliasConstructor = Id {getId = "Lblsym2'LParUndsRParUnds'A'UndsUnds'Int", idLocation = AstLocationFile (FileLocation {fileName = "/home/ttuegel/k/k-distribution/tests/regression-new/concrete-function/././a-kompiled/definition.kore", line = 5031, column = 9})}, symbolOrAliasParams = []}, applicationChildren = [CofreeT (Identity (Pattern {patternSort = SortActualSort (SortActual {sortActualName = Id {getId = "SortInt", idLocation = AstLocationFile (FileLocation {fileName = "/home/ttuegel/k/k-distribution/tests/regression-new/concrete-function/././a-kompiled/definition.kore", line = 3223, column = 250})}, sortActualSorts = []}), freeVariables = fromList []} :< BuiltinF (BuiltinInt (InternalInt {builtinIntSort = SortActualSort (SortActual {sortActualName = Id {getId = "SortInt", idLocation = AstLocationFile (FileLocation {fileName = "/home/ttuegel/k/k-distribution/tests/regression-new/concrete-function/././a-kompiled/definition.kore", line = 3223, column = 250})}, sortActualSorts = []}), builtinIntValue = 222}))))]}))),CofreeT (Identity (Pattern {patternSort = SortActualSort (SortActual {sortActualName = Id {getId = "SortInt", idLocation = AstLocationFile (FileLocation {fileName = "/home/ttuegel/k/k-distribution/tests/regression-new/concrete-function/././a-kompiled/definition.kore", line = 3749, column = 53})}, sortActualSorts = []}), freeVariables = fromList []} :< BuiltinF (BuiltinInt (InternalInt {builtinIntSort = SortActualSort (SortActual {sortActualName = Id {getId = "SortInt", idLocation = AstLocationFile (FileLocation {fileName = "/home/ttuegel/k/k-distribution/tests/regression-new/concrete-function/././a-kompiled/definition.kore", line = 3749, column = 53})}, sortActualSorts = []}), builtinIntValue = 1}))))]})))}
CallStack (from HasCallStack):
  error, called at src/Kore/Step/Axiom/EvaluationStrategy.hs:208:13 in kore-0.0.1.0-FiRPatkPppeJFGRou5ce6o:Kore.Step.Axiom.EvaluationStrategy
[Error] Critical: I/O Error while executing
(./.krun-2019-06-05-09-02-47-160-9ebfd0ba-3201-4f82-9aa3-2d0cb66927ce/result.kore
(No such file or directory))
make: Leaving directory '/home/ttuegel/k/k-distribution/tests/regression-new/concrete-function'
```

### PR DESCRIPTION
**Pull request by vladciobanu**
Fixes #695 

###### Reviewer checklist

- [ ] Test coverage: `stack test --coverage`
- [ ] Public API documentation: `stack haddock`
- [ ] Style conformance: `stylish-haskell`

---

### CODE REVIEW

File: kore/src/Kore/ASTVerifier/SentenceVerifier.hs [hunk 1]
```diff
@@ -260,6 +266,31 @@ verifySymbolSentence indexedModule sentence =
...
 
+    verifyConstructorNotInHookedSort :: Either (Error VerifyError) ()
+    verifyConstructorNotInHookedSort =
+        let
+            symbol = symbolConstructor $ sentenceSymbolSymbol sentence
+            attributes = sentenceSymbolAttributes sentence
+            resultSort = sentenceSymbolResultSort sentence
+            resultSortId = getSortId resultSort
+
+            ctor =
```
Comment (ttuegel) [inline kore/src/Kore/ASTVerifier/SentenceVerifier.hs]: Please add a `TODO` here to look the attribute up in the symbol attribute record.

File: kore/src/Kore/ASTVerifier/SentenceVerifier.hs [hunk 2]
```diff
@@ -260,6 +266,31 @@ verifySymbolSentence indexedModule sentence =
...
+                Attribute.constructorAttribute  `elem` getAttributes attributes
+            sort =
+                join
```
Comment (ttuegel) [inline kore/src/Kore/ASTVerifier/SentenceVerifier.hs]: Would this be clearer using `do`-notation instead of `join`? I had to read this a few times to figure out what is being `join`ed.

**Comment by vladciobanu** [comment]
@ttuegel @virgil-serbanuta  Should I change this to error regardless of whether the sort is hooked?

**Comment by ttuegel** [comment]
Why would that be an error?
