### PR TITLE
Do not return \bottom for unsolved List unification cases

### LINKED ISSUE #2686: Incorrect unification result for LIST.concat
The backend incorrectly gives `\bottom` for this unification problem:

```
\and(concatList(A, B), unitList())
```

Instead, the result should be

```
\and(unitList(), \and(\in(A, unitList()), \in(B, unitList()))
```

### PR DESCRIPTION
**Pull request by ttuegel**
Fixes #2686.

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

File: kore/src/Kore/Builtin/List.hs [hunk 1]
```diff
@@ -446,23 +442,20 @@ unifyEquals
...
+                                unifyEqualsFramedRight builtin1 builtin2 x & lift
                             [x@(Var_ _), InternalList_ builtin2] ->
-                                unifyEqualsFramedLeft builtin1 x builtin2
-                            [_, _] ->
-                                Builtin.unifyEqualsUnsolved
-                                    simplificationType
-                                    dv1
-                                    app
+                                unifyEqualsFramedLeft builtin1 x builtin2 & lift
+                            [_, _] -> empty
```
Comment (ana-pantilie) [inline kore/src/Kore/Builtin/List.hs:458]: How did the old case return `\\bottom`?

**Review by ana-pantilie — APPROVED** [review]
I think this looks good, but I have a question.

File: kore/src/Kore/Builtin/List.hs (hunk 1 above)
Comment (ttuegel) [reply kore/src/Kore/Builtin/List.hs:458]: The old version called `lift empty` instead of `empty`.
