### PR TITLE
Fix "Hooked sorts may not have subsorts" error

### LINKED ISSUE #2155: Missing source location in error message from kprove
Reproduce:
Go to `k/k-distribution/tests/regression-new/bisimulation/examples/spec-refinement/basic`
in `main.k`, remove the line `imports K-REFLECTION`.
Run `make -B KOMPILE_BACKEND=haskell`

Output:

```
/home/hjorthjort/wasm-semantics/dev/deps/k/k-distribution/bin/kompile  --backend haskell  main.k -d .
[Warning] Compiler: Symbol '<c>' defined but not used. Add the 'unused'
attribute if this is intentional.
	Source(/home/hjorthjort/wasm-semantics/dev/deps/k/k-distribution/tests/regression-new/bisimulation/examples/spec-refinement/basic/./main.k)
	Location(22,15,27,5)
[Warning] Compiler: Symbol 'check_MAIN_Pgm' defined but not used. Add the
'unused' attribute if this is intentional.
	Source(/home/hjorthjort/wasm-semantics/dev/deps/k/k-distribution/tests/regression-new/bisimulation/examples/spec-refinement/basic/./main.k)
	Location(59,16,59,22)
[Warning] Compiler: Variable 'M' defined but not used. Prefix variable name
with underscore if this is intentional.
	Source(/home/hjorthjort/wasm-semantics/dev/deps/k/k-distribution/tests/regression-new/bisimulation/examples/spec-refinement/basic/imap.k)
	Location(11,10,11,11)
[Warning] Compiler: Variable 'V' defined but not used. Prefix variable name
with underscore if this is intentional.
	Source(/home/hjorthjort/wasm-semantics/dev/deps/k/k-distribution/tests/regression-new/bisimulation/examples/spec-refinement/basic/imap.k)
	Location(12,20,12,21)
/home/hjorthjort/wasm-semantics/dev/deps/k/k-distribution/bin/kprove main-spec.k --smt-prelude imap.smt2  -d . | diff - main-spec.k.out
kore-exec: [2020-09-17 13:16:29.235035322] Error (ErrorException):
    Error:
      module 'MAIN':
      axiom declaration:
        Hooked sorts may not have subsorts.
    CallStack (from HasCallStack):
      error, called at app/share/GlobalMain.hs:499:36 in main:GlobalMain
[Warning] Critical: Found variable _ on right hand side of rule, not bound on
left hand side. Did you mean "?_"?
Note: this warning will become an error in subsequent releases.
	Source(/home/hjorthjort/wasm-semantics/dev/deps/k/k-distribution/tests/regression-new/bisimulation/examples/spec-refinement/basic/././main-spec.k)
	Location(9,20,9,21)
[Warning] Critical: Found variable _ on right hand side of rule, not bound on
left hand side. Did you mean "?_"?
Note: this warning will become an error in subsequent releases.
	Source(/home/hjorthjort/wasm-semantics/dev/deps/k/k-distribution/tests/regression-new/bisimulation/examples/spec-refinement/basic/././main-spec.k)
	Location(21,24,21,25)
[Warning] Critical: Found variable _ on right hand side of rule, not bound on
left hand side. Did you mean "?_"?
Note: this warning will become an error in subsequent releases.
	Source(/home/hjorthjort/wasm-semantics/dev/deps/k/k-distribution/tests/regression-new/bisimulation/examples/spec-refinement/basic/././main-spec.k)
	Location(38,24,38,25)
[Warning] Compiler: Variable 'M' defined but not used. Prefix variable name
with underscore if this is intentional.
	Source(/home/hjorthjort/wasm-semantics/dev/deps/k/k-distribution/tests/regression-new/bisimulation/examples/spec-refinement/basic/imap.k)
	Location(11,10,11,11)
[Warning] Compiler: Variable 'V' defined but not used. Prefix variable name
with underscore if this is intentional.
	Source(/home/hjorthjort/wasm-semantics/dev/deps/k/k-distribution/tests/regression-new/bisimulation/examples/spec-refinement/basic/imap.k)
	Location(12,20,12,21)
[Error] Critical: Haskell Backend execution failed with code 1 and produced no
output.
0a1
> #True
../../../../../../include/kframework/ktest.mak:95: recipe for target 'main-spec.k' failed
make: *** [main-spec.k] Error 1
```

### PR DESCRIPTION
**Pull request by andreiburdusa**
---
Fixes #2155 
###### Reviewer checklist

- [ ] Test coverage: `stack test --coverage`
- [ ] Public API documentation: `stack haddock`

### CODE REVIEW

**Comment by andreiburdusa** [comment]
The error from the issue is now 
```
kore-exec: [230603] Error (ErrorHookedSortWithSubsort):
    Hooked sorts may not have subsorts.
    Hooked sort:
        Sort'Hash'RuleTag{}
    Its subsort:
        Sort'Hash'KVariable{}
    Location in the Kore file:
        /home/andrei/kore/test/basic/./.kprove-2020-10-07-12-01-20-299-71281ec8-b8ac-4a7e-b282-06fa345984b8/vdefinition.kore 372:218
    Location in the original K file: 
        
```
The axiom source location is not actually shown because of this [issue](https://github.com/kframework/k/issues/1489)

File: kore/src/Kore/ASTVerifier/AttributesVerifier.hs [hunk 1]
```diff
@@ -138,11 +146,18 @@ verifyNoHookAttribute attributes = do
...
-    let isHooked = getHasDomainValues . hasDomainValues <$> supersortsAtts
-    when (or isHooked) $ koreFail "Hooked sorts may not have subsorts."
+verifyNoHookedSupersort indexedModule axiom subsorts = do
+    let isHooked =
+            getHasDomainValues . hasDomainValues
+            . getSortAttributes indexedModule
+            . Subsort.supersort
+        hookedSubsort = find isHooked subsorts
+    for_ hookedSubsort
+        (flip errorHookedSortWithSubsort (Attribute.sourceLocation axiom))
```
Comment (ana-pantilie) [inline kore/src/Kore/ASTVerifier/AttributesVerifier.hs:160]: Would it be better to change the order of the arguments for `errorHookedSortWithSubsort` so that we don't flip them here?

File: test/no-injection-into-hooked/test.k.verify.out.golden [hunk 2]
```diff
@@ -1,4 +1 @@
-Error:
-  module 'TEST':
-  axiom declaration:
-    Hooked sorts may not have subsorts.
+kore-parser: ErrorHookedSortWithSubsort {sort = Subsort {subsort = SortActualSort (SortActual {sortActualName = Id {getId = "SortS", idLocation = AstLocationFile (FileLocation {fileName = "./test-kompiled/definition.kore", line = 209, column = 127})}, sortActualSorts = []}), supersort = SortActualSort (SortActual {sortActualName = Id {getId = "SortInt", idLocation = AstLocationFile (FileLocation {fileName = "./test-kompiled/definition.kore", line = 209, column = 136})}, sortActualSorts = []})}, sourceLocation = SourceLocation {location = Location {start = Nothing, end = Nothing}, source = Source {unSource = Nothing}}}
```
Comment (ana-pantilie) [inline test/no-injection-into-hooked/test.k.verify.out.golden:1]: Does the output look like this because we're not using `koreFail` anymore when throwing the error? What is the reason for that?

Comment (andreiburdusa) [reply test/no-injection-into-hooked/test.k.verify.out.golden]: [This](https://github.com/kframework/kore/pull/2177/commits/6e98f19dfb6acfab388ceb2c2fe0d7152811837d) is some work in progress for pretty printing the error. Does it look like we want to do it?

File: kore/app/parser/Main.hs [hunk 3]
```diff
@@ -183,13 +198,32 @@ mainVerify
...
+
+handleSomeException
+    :: (MonadThrow m, Log.MonadLog m)
+    => SomeException
+    -> m (Either (Error VerifyError) right)
+handleSomeException someException = do
+    case fromException someException of
+        Just (Log.SomeEntry entry) -> Log.logEntry entry
+        Nothing -> errorException someException
+    pure $ Left (koreError (displayException someException))
```
Comment (MirceaS) [inline kore/app/parser/Main.hs:229]: What exactly is going on here?
Won't this line only be executed if the case above takes the `Just` branch? And if so, wouldn't it make more sense to just throw the error inside that branch?

File: kore/src/Kore/ASTVerifier/AttributesVerifier.hs [hunk 4]
```diff
@@ -138,11 +153,30 @@ verifyNoHookAttribute attributes = do
...
+                , "hooked sort:"
+                , show . unparse $ Subsort.supersort s
+                , "its subsort:"
+                , show . unparse $ Subsort.subsort s
+                , "Location in the Kore file:"
+                , show . prettyPrintAstLocation
+                    $ locationFromAst (Subsort.supersort s)
+                , "Location in the original K file: "
+                , show . pretty $ Attribute.sourceLocation axiom
+                ]
```
Comment (ana-pantilie) [inline kore/src/Kore/ASTVerifier/AttributesVerifier.hs:179]: I think `s` should have a more descriptive name, and maybe there could be less indentation here, something like this:

```suggestion
    for_ hookedSubsort $ \sort ->
        koreFail . unlines $
            [ "Hooked sorts may not have subsorts."
            , "hooked sort:"
            , show . unparse $ Subsort.supersort sort
            , "its subsort:"
            , show . unparse $ Subsort.subsort sort
            , "Location in the Kore file:"
            , show . prettyPrintAstLocation
                $ locationFromAst (Subsort.supersort sort)
            , "Location in the original K file: "
            , show . pretty $ Attribute.sourceLocation axiom
            ]
```

**Review by ana-pantilie — APPROVED** [review]

**Review by MirceaS — APPROVED** [review]
Looks good
