### PR TITLE
Regression test script: do not delete golden files

### LINKED ISSUE #2499: Regression test update script should preserve golden file
#2497 is blocked because `scripts/generate-regression-tests.sh` deletes the golden file.

### PR DESCRIPTION
**Pull request by ana-pantilie**
Fixes #2499

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

File: scripts/generate-regression-tests.sh [hunk 1]
```diff
@@ -90,12 +91,13 @@ replace-tests() {
...
     if [ -d $testdir ]
     then
-        rm $testdir/test-*
+        rm $testdir/!(*.golden|Makefile)
     else
         mkdir $testdir
         echo "include \$(CURDIR)/../include.mk" > $testdir/Makefile
         echo "" >> $testdir/Makefile
         echo "test-%.sh.out: \$(TEST_DIR)/test-%-*" >> $testdir/Makefile
+        # TODO: do we want to "make golden" here?
```
Comment (ttuegel) [inline scripts/generate-regression-tests.sh:100]: I think it's OK to do nothing here. The tests will fail when the pull request is added.

**Review by ttuegel — APPROVED** [review]
