### PR TITLE
Error for functions with ensures

### LINKED ISSUE #1193: Haskell:  Rewrite a term to a constrained symbolic variable
Whats the correct way to create a symbmolic Int bounded above and below, using the Haskell backend?I'm trying this:

```
module TEST
    imports INT                                                                 
    syntax Interval ::= "[" Int "," Int "]"                                     
                                                                                
    rule [ I , J ] => ?X:Int                                                    
      ensures ?X >=Int I                                                        
      andBool ?X <=Int J                                                        
endmodule 
```

But I see `kore-exec: Quantifying both the term and the predicate probably means that there's
an error somewhere else.`I tried requires as well

### LINKED ISSUE #1243: Functions with ensures
A function rule's `ensures` clause is currently, and incorrectly, ignored.

See also: #1193

### PR DESCRIPTION
**Pull request by andreiburdusa**
---
Fixes #1243 
###### Reviewer checklist

- [ ] Test coverage: `stack test --coverage`
- [ ] Public API documentation: `stack haddock`

### CODE REVIEW

File: kore/src/Kore/Step/Rule.hs [hunk 1]
```diff
@@ -655,15 +655,20 @@ patternToAxiomPattern attributes pat =
...
+                    pure $ FunctionAxiomPattern $ EqualityRule RulePattern
+                        { left = lhs
+                        , antiLeft = Nothing
+                        , right = rhs
+                        , requires = Predicate.wrapPredicate requires
+                        , ensures = Predicate.makeTruePredicate
+                        , attributes
+                        }
+                _ -> koreFail $ "Found ensures clause:\n"
+                        <> show _ensures
```
Comment (ttuegel) [inline kore/src/Kore/Step/Rule.hs]: We used the initial underscore to prevent the compiler from complaining that `ensures` is not used, but now it is, so we can give this its proper name.

```suggestion
                        <> show ensures
```

File: kore/src/Kore/Step/Rule.hs [hunk 2]
```diff
@@ -655,15 +655,20 @@ patternToAxiomPattern attributes pat =
...
+                TermLike.Top_ _ ->
+                    pure $ FunctionAxiomPattern $ EqualityRule RulePattern
+                        { left = lhs
+                        , antiLeft = Nothing
+                        , right = rhs
+                        , requires = Predicate.wrapPredicate requires
+                        , ensures = Predicate.makeTruePredicate
+                        , attributes
+                        }
+                _ -> koreFail $ "Found ensures clause:\n"
```
Comment (ttuegel) [inline kore/src/Kore/Step/Rule.hs]: Let's use `unlines` instead of the escaped newlines.
