### PR TITLE
Catch exception produced by graph command on mac

### LINKED ISSUE #2817: kore-repl: don't crash when system doesn't support graph visualizer
`kore-repl` shouldn't crash when the system doesn't support the graph visualizer for some reason. We should try to reproduce the crash on a macOS machine by running the `graph` command.

### PR DESCRIPTION
**Pull request by emarzion**
Fixes #2817

Catches the `GVProgramExc` produced by the graph visualizer without terminating the repl session.

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

**Comment by emarzion** [comment]
I have tested this on my mac machine.

File: kore/src/Kore/Repl/Interpreter.hs [hunk 1]
```diff
@@ -1448,6 +1455,22 @@ showDotGraph gr =
...
+    Gr CommonClaimState (Maybe (Seq axiom)) ->
+    IO ()
+showDotGraphCatchException gr =
+    catch (showDotGraph gr) $ \(e :: SomeException) ->
+        hPrint stderr $
+            Pretty.vsep
+                [ "Encountered the following exception:"
+                , Pretty.indent 4 $ fromString $ displayException e
+                , "Please note that the graph command is not\
+                  \ currently supported on MacOS."
```
Comment (ana-pantilie) [inline kore/src/Kore/Repl/Interpreter.hs:1471]: Let's recommend using `graph` with a file name argument, which works on MacOS as well. This saves the graph image to the file.

File: kore/src/Kore/Repl/Interpreter.hs [hunk 2]
```diff
@@ -1448,6 +1455,22 @@ showDotGraph gr =
...
         $ gr
 
+-- | A version of @showDotGraph@ that catches any exceptions.
+showDotGraphCatchException ::
+    From axiom AttrLabel.Label =>
+    From axiom RuleIndex =>
+    Gr CommonClaimState (Maybe (Seq axiom)) ->
+    IO ()
+showDotGraphCatchException gr =
+    catch (showDotGraph gr) $ \(e :: SomeException) ->
```
Comment (ana-pantilie) [inline kore/src/Kore/Repl/Interpreter.hs:1465]: Let's not catch any exception here, we should just catch the exception thrown in this case.

Comment (emarzion) [reply kore/src/Kore/Repl/Interpreter.hs]: Ok, I fixed this so that we are now only catching exceptions coming from from the `GVProgramExc` constructor.  If we wanted to narrow this down more we would need to inspect the message string, which seems a bit brittle to me, but let me know what you think.

Comment (ana-pantilie) [reply kore/src/Kore/Repl/Interpreter.hs]: Looks good, thanks!

**Review by ana-pantilie — APPROVED** [review]
