### PR TITLE
Use new Ceil simplifier

### LINKED ISSUE #2686: Incorrect unification result for LIST.concat
The backend incorrectly gives `\bottom` for this unification problem:

```
\and(concatList(A, B), unitList())
```

Instead, the result should be

```
\and(unitList(), \and(\in(A, unitList()), \in(B, unitList()))
```

### LINKED ISSUE #2689: Sort injections marked "conditionally" simplified
Simplified sort injections are incorrectly marked "conditionally" simplified, so that they are re-simplified every time the side condition changes. The side condition is not considered when simplifying sort injections, so these simplifications are redundant.

### PR DESCRIPTION
**Pull request by ttuegel**
Fixes #2689.
Fixes #2686.

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

**Comment by ttuegel** [comment]
I am very suspicious of these performance numbers because:

1. Everything was fine until I rebased onto master, and
2. I ran all the integration tests locally and they finished in a reasonable amount of time.

If the integration tests time-out on Jenkins again, I will investigate further.

File: kore/src/Kore/Step/Simplification/Condition.hs [hunk 1]
```diff
@@ -71,22 +71,21 @@ unmodified.
...
     SubstitutionSimplifier simplifier ->
     SideCondition RewritingVariableName ->
     Conditional RewritingVariableName any ->
     LogicT simplifier (Conditional RewritingVariableName any)
 simplify SubstitutionSimplifier{simplifySubstitution} sideCondition =
-    normalize >=> worker
+    normalize >=> worker 0
   where
-    worker Conditional{term, predicate, substitution} = do
+    worker count Conditional{term, predicate, substitution} = do
```
Comment (ana-pantilie) [inline kore/src/Kore/Step/Simplification/Condition.hs:83]: Is `count` used anywhere?

File: kore/src/Kore/Step/Simplification/TermLike.hs [hunk 2]
```diff
@@ -477,3 +496,149 @@ ensureSimplifiedCondition repr termLike condition
...
+            pure (OrPattern.fromTermLike termLike)
+        | otherwise =
+            case termLikeF of
+                -- Not implemented:
+                ApplyAliasF _ -> doNotSimplify
+                -- Not simplifiable:
+                EndiannessF _ -> doNotSimplify
+                SignednessF _ -> doNotSimplify
+                -- Handled elsewhere, not a proper term:
+                RewritesF _ -> doNotSimplify
```
Comment (ana-pantilie) [inline kore/src/Kore/Step/Simplification/TermLike.hs:546]: Shouldn't this also throw an error, like the old term simplifier?

File: kore/src/Kore/Step/Simplification/TermLike.hs [hunk 3]
```diff
@@ -477,3 +496,149 @@ ensureSimplifiedCondition repr termLike condition
             , Pretty.indent 2 "while simplifying:"
             , Pretty.indent 4 (unparse termLike)
             ]
+
+-- | Simplify the given 'TermLike'. Do not simplify any side conditions.
+simplifyOnly ::
```
Comment (ana-pantilie) [inline kore/src/Kore/Step/Simplification/TermLike.hs:501]: So, is the plan to replace the old term simplifier with this function?

File: kore/src/Kore/Step/Simplification/Predicate.hs [hunk 4]
```diff
@@ -121,10 +144,19 @@ simplify sideCondition =
                 NotF notF -> simplifyNot =<< traverse worker notF
                 ImpliesF impliesF -> simplifyImplies =<< traverse worker impliesF
                 IffF iffF -> simplifyIff =<< traverse worker iffF
+                CeilF ceilF ->
```
Comment (MirceaS) [inline kore/src/Kore/Step/Simplification/Predicate.hs:147]: Should we have a symmetric case for Floor here as well or is this fine because we're planning to get rid of Floor anyway?

File: kore/src/Kore/Step/Simplification/Predicate.hs [hunk 5]
```diff
@@ -90,28 +98,43 @@ type NormalForm = MultiOr (MultiAnd (Predicate RewritingVariableName))
...
-    loop . MultiOr.singleton . MultiAnd.singleton
+simplify sideCondition original =
+    loop 0 (mkSingleton original)
   where
-    loop :: NormalForm -> simplifier NormalForm
-    loop input = do
-        output <- MultiAnd.traverseOrAnd worker input
-        (if input == output then pure else loop) output
+    limit :: Int
+    limit = 4
```
[the remark this answers is not in the document]
Comment (ttuegel) [reply kore/src/Kore/Step/Simplification/Predicate.hs:110]: This addresses the loop in #2566.

File: kore/src/Kore/Step/Simplification/Condition.hs (hunk 1 above)
Comment (ttuegel) [reply kore/src/Kore/Step/Simplification/Condition.hs:83]: This is left-over from debugging. I suppose we should add a warning here, the same as in the `Predicate` simplifier.

File: kore/src/Kore/Step/Simplification/TermLike.hs (hunk 3 above)
Comment (ttuegel) [reply kore/src/Kore/Step/Simplification/TermLike.hs:501]: Yes, we should eventually replace the old `TermLike` simplifier with this one. There are still some problems with the particular delegates of this function. For example, they are mutually recursive, instead of letting the loop in `simplifyOnly` re-simplify patterns. Also, they don't always delegate to the `Predicate` simplifier like they should.

File: kore/src/Kore/Step/Simplification/Condition.hs [hunk 6]
```diff
@@ -44,7 +44,7 @@ import qualified Kore.Internal.Substitution as Substitution
 import Kore.Rewriting.RewritingVariable (
     RewritingVariableName,
  )
-import qualified Kore.Step.Simplification.Predicate as Predicate
+import {-# SOURCE #-} qualified Kore.Step.Simplification.Predicate as Predicate
```
[the remark this answers is not in the document]
Comment (ttuegel) [reply kore/src/Kore/Step/Simplification/Condition.hs:47]: This resolves a cyclic dependency in the import graph. The cycle will be resolved when the `TermLike` simplifier is finally fixed so that it does not call the `Condition` simplifier.

File: kore/src/Kore/Step/Simplification/Predicate.hs (hunk 5 above)
[the remark this answers is not in the document]
Comment (ttuegel) [reply kore/src/Kore/Step/Simplification/Predicate.hs:110]: No, this should not be passed in. It is an internal detail of the algorithm. I ran this over many proofs and never found a value greater than 1, so I am confident that by setting this limit to 4, we will only see the associated warning when there is a true problem.

File: kore/src/Kore/Step/Simplification/Predicate.hs (hunk 4 above)
Comment (ttuegel) [reply kore/src/Kore/Step/Simplification/Predicate.hs:147]: We should de-sugar `Floor` to `Not Ceil Not`, but we don't use `Floor` in practice, so I thought it wasn't important for getting this merged.

**Review by ana-pantilie — APPROVED** [review]

**Review by MirceaS — APPROVED** [review]
