### PR TITLE
Make SideCondition.assumeDefined total

### LINKED ISSUE #2561: kprove: Crashes when a rule using #Bottom occurs
K Version
---------

```
K version:    5.0.0
Build date:   Mon Apr 19 04:38:10 CDT 2021
```

Description
-----------

kprove crashes with message "cannot assume a \bottom pattern is defined"

Reproduction & input files
-----

```
$ cat test.k
module TEST
    configuration <k> foo </k>
    syntax KItem ::= "foo"
    rule foo => #Bottom 
endmodule

$ kompile --backend haskell test.k

$ cat test-spec.k
module TEST-SPEC
    imports TEST
    imports INT-SYNTAX
    claim <k> foo => 1234 </k> 
endmodule

$ kprove test-spec.k
kore-exec: [142996] Error (ErrorException):
    Internal error: cannot assume a \bottom pattern is defined.
    CallStack (from HasCallStack):
      error, called at src/Kore/Internal/SideCondition.hs:662:17 in kore-0.43.0.0-HgLSPgFtvBzHoiXRxMegel:Kore.Internal.SideCondition
Created bug report: kore-exec.tar.gz
[Error] Internal: Uncaught exception thrown of type NoSuchElementException.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues
(NoSuchElementException: key not found: append)
```

Expected Behavior
-----------------

`kprove` should return `#Top`.

### PR DESCRIPTION
**Pull request by ana-pantilie**
Fixes #2561

Before, we would just syntactically check if the `term` is `\\bottom` before simplifying configurations with the `term` assumed defined. This failed to catch those cases where `\\bottom` appeared inside a symbol application, for example. We decided to avoid this situation entirely by making `SideCondition.assumeDefined` total and handling the `\\bottom` case correctly.

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

**Comment by ttuegel** [comment]
I think this will achieve what we want, for refactoring `assumeDefined`:

``` hs

data Partial a = Bottom | Defined a

instance Semigroup a => Semigroup (Partial a) where
    (<>) Bottom _ = Bottom
    (<>) _ Bottom = Bottom
    (<>) (Defined a) (Defined b) = Defined (a <> b)

instance Monoid a => Monoid (Partial a) where
    mempty = Defined mempty
```

File: kore/src/Kore/Step/Simplification/Pattern.hs [hunk 1]
```diff
@@ -59,19 +63,31 @@ simplifyTopConfiguration ::
...
+            >>= return . removeTopExists
+
+    term = Conditional.term configuration
+    sideCondition = SideCondition.assumeDefined term
+    definedConfiguration =
+        Pattern.andCondition
+            configuration
+            ( makeCeilPredicate term
+                & from @_ @(Condition _)
+            )
```
Comment (ttuegel) [inline kore/src/Kore/Step/Simplification/Pattern.hs:90]: I think this reads a little better, because the most important bits are first and last:

```suggestion
        makeCeilPredicate term
            & from @_ @(Condition _)
            & Pattern.andCondition configuration
```

The important bits are: we are adding a `\ceil`, and we are adding it to the condition.

**Review by ttuegel — APPROVED** [review]
I think this looks great, I just had one nit.
