### PR TITLE
Identify orphan SMT constructors

### LINKED ISSUE #1049: Crashing on missing smtlib expression when merging rules
Steps to reproduce:
```
# only the first time: download the attached definition.txt, then:
mv definition.txt definition.kore
echo e9ec53b0d0d08b3579e685f0d162fd2aa4e01e98e15550af554127828e7e203a > rules.txt
echo 8c5037076555451c7425967181bb86d68c45a908dcb663cbd7265b43b08e1bce >> rules.txt

kore-exec definition.kore --merge-rules rules.txt --module WASM-WITH-K-TERM
```

Error:
```
kore-exec: user error (Unexpected result from the SMT solver:
  Command: (assert (and (not (= <0> |HB_Lblundefined'Unds'WASM-DATA'Unds'Val| ) ) (not <2> ) ) )
  Expected: success
  Result: (error "line 812 column 25: unknown constant HB_Lblundefined'Unds'WASM-DATA'Unds'Val" )
)
```

Also see:
https://github.com/runtimeverification/polkadot-verification/issues/39

### PR DESCRIPTION
**Pull request by virgil-serbanuta**
Fixes #1049 
Fixes runtimeverification/polkadot-verification#39

---

###### Reviewer checklist

- [ ] Test coverage: `stack test --coverage`
- [ ] Public API documentation: `stack haddock`

### CODE REVIEW

File: kore/test/Test/Kore/Step/SMT/Representation/All.hs [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+test_symbolParsing =
+    [ testsForModule "Definition with orphan constructors"
+        (indexModule $ emptyModule "m"
+            `with` sortDeclaration "S"
+            `with`
+                (symbolDeclaration "C" "S" [] `with` [functional, constructor])
+        )
+        [ declarationsAre
+            AST.Declarations
+                { symbols = Map.empty
```
Comment (ttuegel) [inline kore/test/Test/Kore/Step/SMT/Representation/All.hs]: Why is this module regarded as defining no SMT symbols?
