### PR TITLE
Relax the check on total functions

### LINKED ISSUE #2305: Relax total-function check
We must move [this check](https://github.com/kframework/kore/blob/c160ec57e3c9c1c371493452f493f3323a7bf38c/kore/src/Kore/Step/Function/Evaluator.hs#L100) to relax its condition. Currently, it fails when a total function is given `\bottom` as an argument, which should not be an error.

### PR DESCRIPTION
**Pull request by MirceaS**
Fixes #2305 

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [x] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [x] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [x] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

File: kore/src/Kore/Step/Function/Evaluator.hs [hunk 1]
```diff
@@ -97,7 +97,8 @@ evaluateApplication
         & maybeT (unevaluated Nothing) return
         & lift
     for_ canMemoize (recordOrPattern results)
-    when (Symbol.isFunctional symbol && isBottom results) $
+    when (Symbol.isFunctional symbol && isBottom results
+            && not (any isBottom application)) $
```
Comment (ttuegel) [inline kore/src/Kore/Step/Function/Evaluator.hs:101]:
```suggestion
    let unexpectedBottomResult = Symbol.isFunctional symbol && isBottom results
            && not (any isBottom application)
    when unexpectedBottomResult $
```

**Review by ttuegel — APPROVED** [review]
