### PR TITLE
Fix Strict performance

### LINKED ISSUE #2439: Debug performance with Strict

### PR DESCRIPTION
**Pull request by ana-pantilie**
Fixes #2439

- `sum-to-n` from `regression-evm-...` now takes ~36s compared to over 180s on master

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

File: kore/src/Kore/Attribute/Pattern/Simplified.hs [hunk 1]
```diff
@@ -4,7 +4,7 @@ License     : NCSA
 
  -}
 
-{-# LANGUAGE Strict #-}
+-- {-# LANGUAGE Strict #-}
```
Comment (ttuegel) [inline kore/src/Kore/Attribute/Pattern/Simplified.hs:7]:
```suggestion
{-# LANGUAGE NoStrict #-}
```

**Review by ttuegel — CHANGES_REQUESTED** [review]
It seems like we need to make every binding of a `SideCondition.Representation` lazy. Why doesn't it work to make the type itself lazy, [like this](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/exts/strict.html#strict-by-default-data-types)? Otherwise, we must ensure that every binding of such type is strict.

File: kore/src/Kore/Internal/SideCondition/SideCondition.hs [hunk 2]
```diff
@@ -3,6 +3,8 @@ Copyright   : (c) Runtime Verification, 2020
 License     : NCSA
 -}
 
+{-# LANGUAGE StrictData #-}
```
Comment (ttuegel) [inline kore/src/Kore/Internal/SideCondition/SideCondition.hs:6]: Why isn't this just `Strict`? Also, the only data type in this module was made lazy, so why not just `NoStrict` entirely?

File: kore/src/Kore/Internal/SideCondition/SideCondition.hs [hunk 3]
```diff
@@ -34,7 +36,9 @@ import Type.Reflection
     )
 
 data Representation where
-    Representation :: (Ord a, Pretty a) => !(TypeRep a) -> !(Hashed a) -> Representation
+    Representation
+        :: (Ord a, Pretty a)
+        => ~(TypeRep a) -> ~(Hashed a) -> Representation
```
Comment (ttuegel) [inline kore/src/Kore/Internal/SideCondition/SideCondition.hs:41]: It should be completely fine to have the `TypeRep` be strict (it's just a pointer to a single-constructor type with no arguments).

```suggestion
        => !(TypeRep a) -> ~(Hashed a) -> Representation
```

File: kore/src/Kore/Step/Simplification/SubstitutionSimplifier.hs [hunk 4]
```diff
@@ -383,7 +383,7 @@ simplifySubstitutionWorker sideCondition makeAnd' = \substitution -> do
         addPredicate predicate
         return substitution'
 
-    sideConditionRepresentation = SideCondition.toRepresentation sideCondition
+    ~sideConditionRepresentation = SideCondition.toRepresentation sideCondition
```
Comment (ttuegel) [inline kore/src/Kore/Step/Simplification/SubstitutionSimplifier.hs:386]: Does this still need to be explicitly lazy, with `SideCondition.Representation` itself being lazy?

File: kore/src/Kore/Step/Simplification/TermLike.hs [hunk 5]
```diff
@@ -191,7 +191,7 @@ simplify sideCondition = \termLike ->
     simplifyInternalWorker termLike
     >>= ensureSimplifiedResult sideConditionRepresentation termLike
   where
-    sideConditionRepresentation = SideCondition.toRepresentation sideCondition
+    ~sideConditionRepresentation = SideCondition.toRepresentation sideCondition
```
Comment (ttuegel) [inline kore/src/Kore/Step/Simplification/TermLike.hs:194]: I have the same question here as in `Kore.Step.Simplification.SubstitutionSimplifier`.

File: kore/src/Kore/Internal/TermLike/TermLike.hs [hunk 6]
```diff
@@ -948,9 +948,9 @@ traverseVariables adj termLike =
                 (TermLike variable1)
                 (RenamingT variable1 variable2 m (TermLike variable2))
         ->  RenamingT variable1 variable2 m (TermLike variable2)
-    worker (attrs :< termLikeF) = do
-        attrs' <- Attribute.traverseVariables askSomeVariableName attrs
-        let avoiding = freeVariables attrs'
+    worker (~attrs :< termLikeF) = do
```
Comment (ttuegel) [inline kore/src/Kore/Internal/TermLike/TermLike.hs:951]: This is actually a [redundant](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/exts/strict.html#strict-by-default-pattern-bindings) (see "Pattern matching in case expressions..."):

```suggestion
    worker (attrs :< termLikeF) = do
```

File: kore/src/Kore/Internal/SideCondition/SideCondition.hs (hunk 2 above)
Comment (ana-pantilie) [reply kore/src/Kore/Internal/SideCondition/SideCondition.hs:6]: From the link you gave me, I assumed we'd also like to make all modules `StrictData` by default, in the future. Does adding `NoStrict` bypass `StrictData` as well?

File: kore/src/Kore/Step/Simplification/SubstitutionSimplifier.hs (hunk 4 above)
Comment (ana-pantilie) [reply kore/src/Kore/Step/Simplification/SubstitutionSimplifier.hs:386]: `SideCondition.toRepresentation` also [maps](https://github.com/kframework/kore/blob/4195d948dbee2fddd9f056f7bb1d26935e384c6f/kore/src/Kore/Internal/SideCondition.hs#L386) the variables of the `SideCondition` it receives.

**Review by ttuegel — APPROVED** [review]
