### PR TITLE
Print command line and KORE_EXEC_OPTS when parsing fails

### LINKED ISSUE #1597: kore-exec wrong error message for duplicate option
```
$ kore-exec --log L --log L
Invalid option `--log'

Did you mean this?
    --sqlog

Usage: kore-exec [--version] [--search SEARCH_FILE] [--bound BOUND]
                 [--searchType SEARCH_TYPE] [DEFINITION_FILE]
                 [--pattern PATTERN_FILE] [--output PATTERN_OUTPUT_FILE]
                 [--module MODULE] [--smt-timeout SMT_TIMEOUT]
                 [--smt-prelude SMT_PRELUDE] [--smt SOLVER] [--breadth BREADTH]
                 [--depth DEPTH] [--strategy STRATEGY] [--log ARG]
                 [--log-level ARG] ([--enable-log-timestamps] |
                 [--disable-log-timestamps]) [--log-entries ARG]
                 [--debug-applied-rule IDENTIFIER]
                 [--debug-simplification-axiom SIMPLIFICATION_IDENTIFIER]
                 [--debug-simplification-axiom-patterns]
                 [--solver-transcript ARG] [--sqlog FILENAME]
                 [--prove SPEC_FILE] [--spec-module SPEC_MODULE]
                 [--graph-search GRAPH_SEARCH] [--bmc] [--save-proofs ARG]
                 [--merge-rules MERGE_RULES_FILE]
                 [--merge-batch-size MERGE_BATCH_SIZE]
                 [--rts-statistics FILENAME]
  Uses Kore definition in DEFINITION_FILE to execute pattern in PATTERN_FILE.
```

This is getting hard to debug when some options come from `KORE_EXEC_OPTS`.

### LINKED ISSUE #1600: kore-exec: Print entire command line when option parsing fails
We should print the entire command line and `KORE_EXEC_OPTS` when option parsing fails:

```
kore-exec ARGS...
KORE_EXEC_OPTS = ARGS...
```

It would be better to get location information out of `optparse-applicative`, but does not seem to be possible.

### PR DESCRIPTION
**Pull request by andreiburdusa**
---
Fixes #1600 
Fixes #1597

###### Reviewer checklist

- [ ] Test coverage: `stack test --coverage`
- [ ] Public API documentation: `stack haddock`

### CODE REVIEW

File: kore/app/share/GlobalMain.hs [hunk 1]
```diff
@@ -299,16 +309,18 @@ globalCommandLineParser =
...
 
 -- | Run argument parser for local executable
 commandLineParse
-    :: Parser a                -- ^ local options parser
+    :: ForKoreExec
+    -> Parser a                -- ^ local options parser
     -> InfoMod (MainOptions a) -- ^ local parser info modifiers
     -> IO (MainOptions a)
-commandLineParse localCommandLineParser modifiers = do
+commandLineParse (ForKoreExec used) localCommandLineParser modifiers = do
```
Comment (ttuegel) [inline kore/app/share/GlobalMain.hs]: We should use [`ExeName`](https://github.com/kframework/kore/blob/master/kore/src/Kore/Log/KoreLogOptions.hs#L203) here instead, so that we can still give a helpful message when not using `kore-exec`.
