### PR TITLE
Fix map matching with opaque on the right.

### LINKED ISSUE #1376: Cannot write spec about arbitrary map
With the following specification:

```
module SET-BALANCE 
    imports INT 
    imports DOMAINS 
    imports COLLECTIONS 
 
    configuration 
      <set-balance> 
        <k> $ACTION:Action </k> 
        <accounts> 
          <account multiplicity="*" type="Map"> 
            <accountID> .AccountId:AccountId </accountID> 
            <freeBalance> 0 </freeBalance> 
            <reservedBalance> 0 </reservedBalance> 
          </account> 
        </accounts> 
      </set-balance> 
 
    syntax Action ::= ".Action" | EntryAction 
    syntax EntryAction ::= ".EntryAction" 
 
    syntax AccountId ::= ".AccountId" | Int 
 // --------------------------------------- 
 
    syntax Int ::= "total_balance" "(" AccountId ")" [function, functional] 
 // ----------------------------------------------------------------------- 
    rule total_balance(WHO) => free_balance(WHO) +Int reserved_balance(WHO) 
 
    syntax Int ::= "free_balance" "(" AccountId ")" [function, functional] 
 // ---------------------------------------------------------------------- 
    rule    free_balance(_)   => 0 [owise] 
    rule [[ free_balance(WHO) => FREE_BALANCE ]] 
         <account> 
           <accountID> WHO </accountID> 
           <freeBalance> FREE_BALANCE </freeBalance> 
           ... 
         </account> 
 
    syntax Int ::= "reserved_balance" "(" AccountId ")" [function, functional] 
 // -------------------------------------------------------------------------- 
    rule    reserved_balance(_)   => 0 [owise] 
    rule [[ reserved_balance(WHO) => FREE_BALANCE ]] 
         <account> 
           <accountID> WHO </accountID> 
           <reservedBalance> FREE_BALANCE </reservedBalance> 
           ... 
         </account> 
endmodule 
```

We cannot prove the following claim:

```

```requires "set-balance.k" 
 
module VERIFICATION 
    imports SET-BALANCE 
 
    syntax EntryAction ::= totalBalance ( AccountId ) 
    rule <k> totalBalance(AID) => total_balance(AID) ... </k> 
endmodule 
 
module SET-BALANCE-SPEC 
    imports VERIFICATION 
       
    rule <k> totalBalance(AID) => 50 ... </k> 
         <accounts> 
           <account> 
             <accountID> AID </accountID> 
             <freeBalance> 30 </freeBalance> 
             <reservedBalance> 20 </reservedBalance> 
             ... 
           </account> 
           ... 
         </accounts> 
endmodule 
```

Because it cannot prove that the `AccountCellMap` is well defined (I think):

```
  #Ceil ( <account>
    <accountID>
      AID
    </accountID>
    <freeBalance>
      30
    </freeBalance>
    <reservedBalance>
      20
    </reservedBalance>
  </account> DotVar3 )
#And
  <set-balance>
    <k>
      free_balance ( AID ) <set-balance>
        <k>
          totalBalance ( AID ) ~> DotVar2
        </k>
        <accounts>
          <account>
            <accountID>
              AID
            </accountID>
            <freeBalance>
              30
            </freeBalance>
            <reservedBalance>
              20
            </reservedBalance>
          </account> DotVar3
        </accounts>
      </set-balance> +Int reserved_balance ( AID ) <set-balance>
        <k>
          totalBalance ( AID ) ~> DotVar2
        </k>
        <accounts>
          <account>
            <accountID>
              AID
            </accountID>
            <freeBalance>
              30
            </freeBalance>
            <reservedBalance>
              20
            </reservedBalance>
          </account> DotVar3
        </accounts>
      </set-balance> ~> DotVar2
    </k>
    <accounts>
      <account>
        <accountID>
          AID
        </accountID>
        <freeBalance>
          30
        </freeBalance>
        <reservedBalance>
          20
        </reservedBalance>
      </account> DotVar3
    </accounts>
  </set-balance>
```

I think it should be safe to assume that we start in an initial state where the `*CellMap`s are well-defined, which means that the keys are distinct. If not, I can add explicit side-conditions to make it so, but what side conditions should I add?

Attaching the relevant `*.kore` files.
[kore.tar.txt](https://github.com/kframework/kore/files/3985366/kore.tar.txt)

### PR DESCRIPTION
**Pull request by virgil-serbanuta**
Fixes #1376 

---

###### Reviewer checklist

- [ ] Test coverage: `stack test --coverage`
- [ ] Public API documentation: `stack haddock`

### CODE REVIEW

File: kore/src/Kore/Step/Axiom/Matcher.hs [hunk 1]
```diff
@@ -668,16 +668,22 @@ matchNormalizedAc
...
+        [] -> do
+            Monad.guard (null opaque2)
             Monad.guard (null excessConcrete2)
             Monad.guard (null excessAbstract2)
-        [frame1] -> push (Pair frame1 normalized2')
-        _        -> empty
+        [frame1]
+          | null excessAbstract2
+          , null excessConcrete2
+          , [frame2] <- opaque2 ->
```
Comment (ttuegel) [inline kore/src/Kore/Step/Axiom/Matcher.hs]: Would it be difficult to generalize this to accept any number of opaque collections in the second argument? I'm not sure how much that will happen in practice, though.

Comment (virgil-serbanuta) [reply kore/src/Kore/Step/Axiom/Matcher.hs]: This should be handled below (the otherwise case). Having a single opaque thing means that we can unpack it and have a somewhat optimized unification which is nice if the two opaque things are variables (e.g. we get `varMap1=varMap2` instead of `varMap1=wrap-in-normalized-ac(varMap2)`), but that unwrapping does not work with two opaque things.

Comment (ttuegel) [reply kore/src/Kore/Step/Axiom/Matcher.hs]: Oh, I understand now. Thanks!
