### PR TITLE
WarnIfLowProductivity: suggest a corrective action

### LINKED ISSUE #2037: WarnIfLowProductivity does not suggest a corrective action
All warnings should suggest a corrective action; in this case, the corrective action is to file a bug report, but probably not if total run time is short.

Related: #2036

### PR DESCRIPTION
**Pull request by andreiburdusa**
---
Fixes #2037 
###### Reviewer checklist

- [ ] Test coverage: `stack test --coverage`
- [ ] Public API documentation: `stack haddock`

### CODE REVIEW

File: kore/src/Kore/Log/WarnIfLowProductivity.hs [hunk 1]
```diff
@@ -25,9 +25,12 @@ newtype WarnIfLowProductivity =
...
     pretty (WarnIfLowProductivity productivityPercent) =
-        Pretty.hsep
-            [ "Warning! Poor performance: productivity dropped to aprox."
-            , Pretty.pretty productivityPercent <> "%"
+        Pretty.vsep
+            [ Pretty.hsep
+                [ "Warning! Poor performance: productivity dropped to aprox."
+                , Pretty.pretty productivityPercent <> "%."
+                ]
+            , "Please file a bug report."
```
Comment (ttuegel) [inline kore/src/Kore/Log/WarnIfLowProductivity.hs:33]: I want to include the URL so that the user can click on it in the terminal and go directly there:

```suggestion
            [ Pretty.hsep
                [ "Productivity dropped to:"
                , Pretty.pretty productivityPercent <> "%"
                ]
            , "Poor productivity may indicate a performance bug."
            , "Please file a bug report: https://github.com/kframework/kore/issues"
```

I removed the `Warning!` because that is already included by setting the log level below.
