### PR TITLE
No bug report on UserInterrupt

### LINKED ISSUE #1996: Do not create a bug report when user interrupts backend
The backend perceives the interrupt signal as an exception and generates a bug report. This is not the desired behavior.

### PR DESCRIPTION
**Pull request by andreiburdusa**
---
Fixes #1996 
###### Reviewer checklist

- [ ] Test coverage: `stack test --coverage`
- [ ] Public API documentation: `stack haddock`

### CODE REVIEW

File: kore/src/Kore/BugReport.hs [hunk 1]
```diff
@@ -79,7 +83,7 @@ writeBugReportArchive base tar = do
 {- | Run the inner action with a temporary directory holding the bug report.
 
 The bug report will be saved as an archive if that was requested by the user, or
-if there is an error in the inner action.
+if there is an error in the inner action other than `UserInterrupt`.
```
Comment (ttuegel) [inline kore/src/Kore/BugReport.hs:86]:
```suggestion
if there is an error in the inner action other than 'UserInterrupt'.
```
