### PR TITLE
Fix ConstructorLike for maps

### LINKED ISSUE #1393: `.Map` is not considered as concrete
In evm-semantics, I marked the following rule as concrete:
```
    syntax Map ::= Map "[" Int ":=" ByteArray "]" [function, klabel(mapWriteBytes)]
 // -------------------------------------------------------------------------------
    rule WM[ N := WS ] => WM [ N := WS, 0, #sizeByteArray(WS) ] [concrete]
```
During the execution, the prover reported the following error:
```
Stepper evaluation errored.
WithConfiguration ...
Unification case that should be handled somewhere else:
attempting normalized unification with a 
non-element-variable opaque term or 
non-function maps could lead to infinite loops.
first=/* builtin: */ Lbl'Stop'Map{}()
second=Lbl'UndsLSqBUndsColnEqlsUndsRSqBUnds'EVM-TYPES'Unds'Map'Unds'Map'Unds'Int'Unds'ByteArray{}(
    /* builtin: */ Lbl'Stop'Map{}(),
    /* builtin: */ \dv{SortInt{}}("64"),
    \dv{SortBytes{}}(
        "0000000000000000000000000000000000000000000000000000000000000060"
    )
)
```
and I found that term `.Map [ 64 := b"0000000000000000000000000000000000000000000000000000000000000060" ]` is not evaluated in the configuration.

### PR DESCRIPTION
**Pull request by virgil-serbanuta**
Fixes #1393 

---

###### Reviewer checklist

- [ ] Test coverage: `stack test --coverage`
- [ ] Public API documentation: `stack haddock`

### CODE REVIEW

File: kore/src/Kore/Attribute/Pattern/ConstructorLike.hs [hunk 1]
```diff
@@ -193,15 +195,42 @@ A builtin value is not technically a constructor, but it is constructor-like for
...
+            { elementsWithVariables = []
+            , concreteElements
+            , opaque = []
+            }
+              | all pairIsConstructorLike concreteElementsList
+                -> ConstructorLike . Just $ ConstructorLikeHead
+              where
+                concreteElementsList = Map.toList concreteElements
+                pairIsConstructorLike (key, value) =
+                    isConstructorLike key && isConstructorLike value
```
Comment (ttuegel) [inline kore/src/Kore/Attribute/Pattern/ConstructorLike.hs]: Why do we need to check the `key`? It should always be constructor-like. If we are going to check, I think it should at least be an assertion, but if we don't check, then we also don't need the `HasConstructorLike` abstraction.

Comment (virgil-serbanuta) [reply kore/src/Kore/Attribute/Pattern/ConstructorLike.hs]: We don't, but I thought it's safer to check it, especially since the requirements for the key changed in the past. You're right, an assertion makes more sense, so I changed it to that.

**Comment by yzhang90** [comment]
it solves my problem. thanks

File: kore/src/Kore/Attribute/Pattern/ConstructorLike.hs [hunk 2]
```diff
@@ -245,3 +274,23 @@ instance Diff ConstructorLikeHead where
...
 instance Hashable ConstructorLikeHead
+
+class HasConstructorLike a where
+    extractConstructorLike :: a -> ConstructorLike
+
+    isConstructorLike :: a -> Bool
+    isConstructorLike a = case extractConstructorLike a of
+        (ConstructorLike constructorLike) -> isJust constructorLike
+
+    assertConstructorLike :: String -> a -> b -> b
```
Comment (ttuegel) [inline kore/src/Kore/Attribute/Pattern/ConstructorLike.hs]: Does this need to be a member of the class? Would we ever want to override it?

File: kore/test/Test/Kore/Attribute/Pattern/ConstructorLike.hs [hunk 3]
```diff
@@ -3,31 +3,53 @@ module Test.Kore.Attribute.Pattern.ConstructorLike
     ) where
 
 import Test.Tasty
-import Test.Tasty.HUnit
+--import Test.Tasty.HUnit
```
Comment (ttuegel) [inline kore/test/Test/Kore/Attribute/Pattern/ConstructorLike.hs]:
```suggestion
```
