### PR TITLE
Fix String2Base evaluation bug

### LINKED ISSUE #2546: STRING.String2Base should not return \bottom where unimplemented
`STRING.String2Base` should emit a warning when it is not implemented for a particular base, instead of returning `\bottom`.

### PR DESCRIPTION
**Pull request by MirceaS**
Fixes #2546 

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

File: kore/src/Kore/Builtin/String.hs [hunk 1]
```diff
@@ -297,26 +298,25 @@ evalFind = Builtin.functionEvaluator evalFind0
...
-        let readN =
-                case _base of
-                    -- no builtin reader for number in octal notation
-                    8 -> \s ->
-                        case readOct $ Text.unpack s of
-                            [(result, "")] -> Right (result, "")
-                            _ -> Left ""
-                    10 -> Text.signed Text.decimal
-                    16 -> Text.signed Text.hexadecimal
-                    _ -> const empty
```
Comment (ana-pantilie) [inline kore/src/Kore/Builtin/String.hs:314]: Just so I'm 100% sure I understand, what caused this function to return `\\bottom` before, instead of just not evaluating?

File: kore/src/Kore/Builtin/String.hs [hunk 2]
```diff
@@ -297,26 +298,25 @@ evalFind = Builtin.functionEvaluator evalFind0
     evalFind0 _ _ _ = Builtin.wrongArity findKey
 
 evalString2Base :: BuiltinAndAxiomSimplifier
-evalString2Base = Builtin.functionEvaluator evalString2Base0
+evalString2Base = Builtin.functionEvaluatorWithApp evalString2Base0
```
Comment (ttuegel) [inline kore/src/Kore/Builtin/String.hs:301]: Why not just `Builtin.applicationEvaluator`?

File: kore/src/Kore/Builtin/String.hs (hunk 1 above)
Comment (ana-pantilie) [reply kore/src/Kore/Builtin/String.hs:314]: Got it, thanks!

**Review by ana-pantilie — APPROVED** [review]

**Review by andreiburdusa — APPROVED** [review]

**Review by ttuegel — APPROVED** [review]
