### PR TITLE
Search: use matching instead of unification

### LINKED ISSUE #2879: Bug: kore-match-disjunction returns \bottom when it should not
How to run:

The --bug-report flag seems to generate an archive that is completely empty except for an empty text file, so I pushed the files involved to the search-example branch of kframework/k. You can reproduce by running cd k-distribution/tests/regression-new/imp++-llvm/; kore-match-disjunction definition.kore --module IMP --disjunction disjunction.kore --match pattern.kore

Expected behavior: should return 4 solutions.
Actual behavior: returns `\bottom`

### PR DESCRIPTION
**Pull request by andreiburdusa**
Fixes #2879 

### Estimate: December, 2

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

File: kore/src/Kore/Rewrite/Search.hs [hunk 1]
```diff
@@ -130,28 +128,25 @@ matchWith ::
...
             merged <-
                 mergePredicatesAndSubstitutions
                     sideCondition
-                    [ Conditional.predicate predSubst
+                    [ predicate
                     , Conditional.predicate e1
                     , Conditional.predicate e2
                     ]
-                    [Conditional.substitution predSubst]
+                    [from substitution]
```
Comment (ana-pantilie) [inline kore/src/Kore/Rewrite/Search.hs:149]: Please add a type annotation here to indicate the type transformation.

**Review by ana-pantilie — APPROVED** [review]
Just had a small comment.
